// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AddUsersToCampaignData,
  AddUsersToCampaignErrors,
  AddUsersToCampaignResponses,
  ApproveUserData,
  ApproveUserErrors,
  ApproveUserResponses,
  ApproveUsersBulkData,
  ApproveUsersBulkErrors,
  ApproveUsersBulkResponses,
  AssignReviewersData,
  AssignReviewersErrors,
  AssignReviewersResponses,
  AssignTasksToUsersData,
  AssignTasksToUsersErrors,
  AssignTasksToUsersResponses,
  CompleteAnnotationTaskData,
  CompleteAnnotationTaskErrors,
  CompleteAnnotationTaskResponses,
  CreateAnnotationOpenmodeData,
  CreateAnnotationOpenmodeErrors,
  CreateAnnotationOpenmodeResponses,
  CreateCampaignData,
  CreateCampaignErrors,
  CreateCampaignResponses,
  CreateImageryData,
  CreateImageryErrors,
  CreateImageryResponses,
  CreateNewCanvasLayoutForImageryData,
  CreateNewCanvasLayoutForImageryErrors,
  CreateNewCanvasLayoutForImageryResponses,
  CreateTimeseriesForCampaignData,
  CreateTimeseriesForCampaignErrors,
  CreateTimeseriesForCampaignResponses,
  DeleteAnnotationData,
  DeleteAnnotationErrors,
  DeleteAnnotationResponses,
  DeleteAnnotationTasksData,
  DeleteAnnotationTasksErrors,
  DeleteAnnotationTasksResponses,
  DeleteCampaignData,
  DeleteCampaignErrors,
  DeleteCampaignResponses,
  DeleteImageryData,
  DeleteImageryErrors,
  DeleteImageryResponses,
  DeleteTimeseriesData,
  DeleteTimeseriesErrors,
  DeleteTimeseriesResponses,
  DemoteAuthorativeReviewerData,
  DemoteAuthorativeReviewerErrors,
  DemoteAuthorativeReviewerResponses,
  DemoteCampaignAdminData,
  DemoteCampaignAdminErrors,
  DemoteCampaignAdminResponses,
  DenyUserData,
  DenyUserErrors,
  DenyUserResponses,
  DenyUsersBulkData,
  DenyUsersBulkErrors,
  DenyUsersBulkResponses,
  EditUserInfoData,
  EditUserInfoErrors,
  EditUserInfoResponses,
  ExportAnnotationsData,
  ExportAnnotationsErrors,
  ExportAnnotationsGeojsonData,
  ExportAnnotationsGeojsonErrors,
  ExportAnnotationsGeojsonResponses,
  ExportAnnotationsResponses,
  GenerateTasksFromSamplingData,
  GenerateTasksFromSamplingErrors,
  GenerateTasksFromSamplingResponses,
  GetAllAnnotationsForCampaignData,
  GetAllAnnotationsForCampaignErrors,
  GetAllAnnotationsForCampaignResponses,
  GetAllAnnotationTasksData,
  GetAllAnnotationTasksErrors,
  GetAllAnnotationTasksResponses,
  GetCampaignData,
  GetCampaignErrors,
  GetCampaignResponses,
  GetCampaignStatisticsEndpointData,
  GetCampaignStatisticsEndpointErrors,
  GetCampaignStatisticsEndpointResponses,
  GetCampaignUsersData,
  GetCampaignUsersErrors,
  GetCampaignUsersResponses,
  GetCampaignWithImageryWindowsData,
  GetCampaignWithImageryWindowsErrors,
  GetCampaignWithImageryWindowsResponses,
  GetTimeseriesCreationOptionsData,
  GetTimeseriesCreationOptionsResponses,
  GetTimeseriesDataData,
  GetTimeseriesDataErrors,
  GetTimeseriesDataResponses,
  GetTimeseriesForCampaignData,
  GetTimeseriesForCampaignErrors,
  GetTimeseriesForCampaignResponses,
  GrantAdminData,
  GrantAdminErrors,
  GrantAdminResponses,
  GrantAdminSingleData,
  GrantAdminSingleErrors,
  GrantAdminSingleResponses,
  IngestAnnotationTasksFromCsvData,
  IngestAnnotationTasksFromCsvErrors,
  IngestAnnotationTasksFromCsvResponses,
  ListAllCampaignsData,
  ListAllCampaignsResponses,
  ListUsersData,
  ListUsersResponses,
  MakeUserAuthorativeReviewerData,
  MakeUserAuthorativeReviewerErrors,
  MakeUserAuthorativeReviewerResponses,
  MakeUserCampaignAdminData,
  MakeUserCampaignAdminErrors,
  MakeUserCampaignAdminResponses,
  MeData,
  MeResponses,
  RemoveUserFromCampaignData,
  RemoveUserFromCampaignErrors,
  RemoveUserFromCampaignResponses,
  RevokeAdminData,
  RevokeAdminErrors,
  RevokeAdminResponses,
  RevokeAdminSingleData,
  RevokeAdminSingleErrors,
  RevokeAdminSingleResponses,
  RevokeUserData,
  RevokeUserErrors,
  RevokeUserResponses,
  RevokeUsersBulkData,
  RevokeUsersBulkErrors,
  RevokeUsersBulkResponses,
  UnassignUserFromTask2Data,
  UnassignUserFromTask2Errors,
  UnassignUserFromTask2Responses,
  UnassignUserFromTaskData,
  UnassignUserFromTaskErrors,
  UnassignUserFromTaskResponses,
  UpdateAnnotationOpenmodeData,
  UpdateAnnotationOpenmodeErrors,
  UpdateAnnotationOpenmodeResponses,
  UpdateCampaignBboxData,
  UpdateCampaignBboxErrors,
  UpdateCampaignBboxResponses,
  UpdateCampaignNameData,
  UpdateCampaignNameErrors,
  UpdateCampaignNameResponses,
  UpdateEmbeddingYearData,
  UpdateEmbeddingYearErrors,
  UpdateEmbeddingYearResponses,
  UpdateImageryData,
  UpdateImageryErrors,
  UpdateImageryResponses,
  ValidateAnnotationSubmissionData,
  ValidateAnnotationSubmissionErrors,
  ValidateAnnotationSubmissionResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Me
 *
 * Get current authenticated user's details.
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) =>
  (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options,
  });

/**
 * List Users
 *
 * List all users in the system (admin only).
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users',
    ...options,
  });

/**
 * Edit User Info
 *
 * Edit user display name.
 *
 * Users can edit their own information.
 * Admins can edit any user's information.
 */
export const editUserInfo = <ThrowOnError extends boolean = false>(
  options: Options<EditUserInfoData, ThrowOnError>
) =>
  (options.client ?? client).patch<EditUserInfoResponses, EditUserInfoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}',
    ...options,
  });

/**
 * Approve User
 *
 * Approve a single user (admin only).
 *
 * Grants approval role to the specified user.
 */
export const approveUser = <ThrowOnError extends boolean = false>(
  options: Options<ApproveUserData, ThrowOnError>
) =>
  (options.client ?? client).post<ApproveUserResponses, ApproveUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}/approve',
    ...options,
  });

/**
 * Revoke User
 *
 * Revoke approval from a single user (admin only).
 *
 * Removes approval role from the specified user.
 */
export const revokeUser = <ThrowOnError extends boolean = false>(
  options: Options<RevokeUserData, ThrowOnError>
) =>
  (options.client ?? client).post<RevokeUserResponses, RevokeUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}/revoke',
    ...options,
  });

/**
 * Deny User
 *
 * Deny (delete) an unapproved user from the system (admin only).
 *
 * Permanently removes users who have not been approved yet.
 * Cannot be used on approved users or admins.
 */
export const denyUser = <ThrowOnError extends boolean = false>(
  options: Options<DenyUserData, ThrowOnError>
) =>
  (options.client ?? client).post<DenyUserResponses, DenyUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}/deny',
    ...options,
  });

/**
 * Approve Users Bulk
 *
 * Approve multiple users (admin only).
 *
 * Grants approval role to all specified users in a single transaction.
 */
export const approveUsersBulk = <ThrowOnError extends boolean = false>(
  options: Options<ApproveUsersBulkData, ThrowOnError>
) =>
  (options.client ?? client).post<ApproveUsersBulkResponses, ApproveUsersBulkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/approve',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke Users Bulk
 *
 * Revoke approval from multiple users (admin only).
 *
 * Removes approval role from all specified users in a single transaction.
 */
export const revokeUsersBulk = <ThrowOnError extends boolean = false>(
  options: Options<RevokeUsersBulkData, ThrowOnError>
) =>
  (options.client ?? client).post<RevokeUsersBulkResponses, RevokeUsersBulkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Deny Users Bulk
 *
 * Deny (delete) multiple unapproved users from the system (admin only).
 *
 * Permanently removes users who have not been approved yet.
 * Users who are already approved or are admins will not be deleted.
 */
export const denyUsersBulk = <ThrowOnError extends boolean = false>(
  options: Options<DenyUsersBulkData, ThrowOnError>
) =>
  (options.client ?? client).post<DenyUsersBulkResponses, DenyUsersBulkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/deny',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Grant Admin Single
 *
 * Grant admin role to a single user (admin only).
 *
 * Grants admin and approval roles to the specified user.
 */
export const grantAdminSingle = <ThrowOnError extends boolean = false>(
  options: Options<GrantAdminSingleData, ThrowOnError>
) =>
  (options.client ?? client).post<GrantAdminSingleResponses, GrantAdminSingleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}/grant-admin',
    ...options,
  });

/**
 * Revoke Admin Single
 *
 * Revoke admin role from a single user (admin only).
 *
 * Removes admin role from the specified user.
 * Prevents revoking admin from the last admin user.
 */
export const revokeAdminSingle = <ThrowOnError extends boolean = false>(
  options: Options<RevokeAdminSingleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RevokeAdminSingleResponses,
    RevokeAdminSingleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/{user_id}/revoke-admin',
    ...options,
  });

/**
 * Grant Admin
 *
 * Grant admin role to multiple users (admin only).
 *
 * Grants admin and approval roles to all specified users in a single transaction.
 */
export const grantAdmin = <ThrowOnError extends boolean = false>(
  options: Options<GrantAdminData, ThrowOnError>
) =>
  (options.client ?? client).post<GrantAdminResponses, GrantAdminErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/grant-admin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke Admin
 *
 * Revoke admin role from multiple users (admin only).
 *
 * Removes admin role from all specified users in a single transaction.
 * Prevents revoking admin from all users if it would leave no admins.
 */
export const revokeAdmin = <ThrowOnError extends boolean = false>(
  options: Options<RevokeAdminData, ThrowOnError>
) =>
  (options.client ?? client).post<RevokeAdminResponses, RevokeAdminErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/users/revoke-admin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List All Campaigns
 */
export const listAllCampaigns = <ThrowOnError extends boolean = false>(
  options?: Options<ListAllCampaignsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAllCampaignsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/',
    ...options,
  });

/**
 * Create Campaign
 */
export const createCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateCampaignData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateCampaignResponses, CreateCampaignErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Campaign
 *
 * Delete a campaign and all associated data (imagery, timeseries, annotations, etc.).
 * Only campaign admins can delete campaigns.
 */
export const deleteCampaign = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCampaignData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteCampaignResponses, DeleteCampaignErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}',
    ...options,
  });

/**
 * Get Campaign
 */
export const getCampaign = <ThrowOnError extends boolean = false>(
  options: Options<GetCampaignData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCampaignResponses, GetCampaignErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}',
    ...options,
  });

/**
 * Add Users To Campaign
 */
export const addUsersToCampaign = <ThrowOnError extends boolean = false>(
  options: Options<AddUsersToCampaignData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AddUsersToCampaignResponses,
    AddUsersToCampaignErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/assign-users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Campaign With Imagery Windows
 *
 * Get campaign with detailed imagery windows and layouts (both default and personal)
 */
export const getCampaignWithImageryWindows = <ThrowOnError extends boolean = false>(
  options: Options<GetCampaignWithImageryWindowsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCampaignWithImageryWindowsResponses,
    GetCampaignWithImageryWindowsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/detailed',
    ...options,
  });

/**
 * Make User Campaign Admin
 */
export const makeUserCampaignAdmin = <ThrowOnError extends boolean = false>(
  options: Options<MakeUserCampaignAdminData, ThrowOnError>
) =>
  (options.client ?? client).post<
    MakeUserCampaignAdminResponses,
    MakeUserCampaignAdminErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/make-user-admin',
    ...options,
  });

/**
 * Make User Authorative Reviewer
 *
 * Give a user the authorative reviewer role, enabling him to review other annotations.
 */
export const makeUserAuthorativeReviewer = <ThrowOnError extends boolean = false>(
  options: Options<MakeUserAuthorativeReviewerData, ThrowOnError>
) =>
  (options.client ?? client).post<
    MakeUserAuthorativeReviewerResponses,
    MakeUserAuthorativeReviewerErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/make-user-authorative-reviewer',
    ...options,
  });

/**
 * Get Campaign Users
 */
export const getCampaignUsers = <ThrowOnError extends boolean = false>(
  options: Options<GetCampaignUsersData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCampaignUsersResponses, GetCampaignUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/users',
    ...options,
  });

/**
 * Update Campaign Name
 */
export const updateCampaignName = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCampaignNameData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateCampaignNameResponses,
    UpdateCampaignNameErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/name',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Campaign Bbox
 */
export const updateCampaignBbox = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCampaignBboxData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateCampaignBboxResponses,
    UpdateCampaignBboxErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/bbox',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Embedding Year
 *
 * Set or change the year used for satellite embeddings.
 *
 * When the year changes, all existing embeddings are deleted and
 * re-fetched for the new year.  This can take some time for large
 * campaigns.
 */
export const updateEmbeddingYear = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEmbeddingYearData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateEmbeddingYearResponses,
    UpdateEmbeddingYearErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/embedding-year',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove User From Campaign
 *
 * Remove a user from a campaign (admin only).
 *
 * Note: This only removes the user's access to the campaign.
 * All annotations created by the user are preserved and remain in the campaign.
 */
export const removeUserFromCampaign = <ThrowOnError extends boolean = false>(
  options: Options<RemoveUserFromCampaignData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveUserFromCampaignResponses,
    RemoveUserFromCampaignErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/users/{user_id}',
    ...options,
  });

/**
 * Demote Campaign Admin
 *
 * Demote an admin user to member role
 */
export const demoteCampaignAdmin = <ThrowOnError extends boolean = false>(
  options: Options<DemoteCampaignAdminData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DemoteCampaignAdminResponses,
    DemoteCampaignAdminErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/demote-admin',
    ...options,
  });

/**
 * Demote Authorative Reviewer
 *
 * Demote an authorative reviewer to basic member
 */
export const demoteAuthorativeReviewer = <ThrowOnError extends boolean = false>(
  options: Options<DemoteAuthorativeReviewerData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DemoteAuthorativeReviewerResponses,
    DemoteAuthorativeReviewerErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/demote-auth-reviewer',
    ...options,
  });

/**
 * Assign Tasks To Users
 *
 * Assign multiple annotation tasks to different users in bulk. Supports multiple reviewers per task.
 */
export const assignTasksToUsers = <ThrowOnError extends boolean = false>(
  options: Options<AssignTasksToUsersData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AssignTasksToUsersResponses,
    AssignTasksToUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/assign-tasks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unassign User From Task
 *
 * Remove a user's assignment from a specific task.
 */
export const unassignUserFromTask = <ThrowOnError extends boolean = false>(
  options: Options<UnassignUserFromTaskData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UnassignUserFromTaskResponses,
    UnassignUserFromTaskErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/tasks/{task_id}/unassign-user/{user_id}',
    ...options,
  });

/**
 * Assign Reviewers
 *
 * Assign reviewers to tasks using different patterns:
 * - 'percentage': Assign reviewers to X% of tasks
 * - 'manual': Manually assign specific reviewers to specific tasks
 * - 'fixed': Assign N reviewers to M tasks
 */
export const assignReviewers = <ThrowOnError extends boolean = false>(
  options: Options<AssignReviewersData, ThrowOnError>
) =>
  (options.client ?? client).post<AssignReviewersResponses, AssignReviewersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/assign-reviewers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unassign User From Task
 *
 * Remove a user assignment from a specific task
 */
export const unassignUserFromTask2 = <ThrowOnError extends boolean = false>(
  options: Options<UnassignUserFromTask2Data, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UnassignUserFromTask2Responses,
    UnassignUserFromTask2Errors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/tasks/{task_id}/users/{user_id}',
    ...options,
  });

/**
 * Delete Annotation Tasks
 *
 * Delete multiple annotation tasks from a campaign
 */
export const deleteAnnotationTasks = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnnotationTasksData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAnnotationTasksResponses,
    DeleteAnnotationTasksErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotation-tasks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get All Annotation Tasks
 */
export const getAllAnnotationTasks = <ThrowOnError extends boolean = false>(
  options: Options<GetAllAnnotationTasksData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAllAnnotationTasksResponses,
    GetAllAnnotationTasksErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotation-tasks',
    ...options,
  });

/**
 * Get Campaign Statistics Endpoint
 *
 * Get comprehensive statistics for a campaign.
 *
 * Returns:
 * - Overall campaign metrics (total annotations, users, tasks)
 * - Krippendorff's Alpha for inter-annotator agreement
 * - Overall confidence and label distributions
 * - Per-user statistics including:
 * - Total annotations
 * - Average confidence
 * - Confidence distribution
 * - Label distribution
 * - Agreement with majority vote
 */
export const getCampaignStatisticsEndpoint = <ThrowOnError extends boolean = false>(
  options: Options<GetCampaignStatisticsEndpointData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCampaignStatisticsEndpointResponses,
    GetCampaignStatisticsEndpointErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/statistics',
    ...options,
  });

/**
 * Complete Annotation Task
 */
export const completeAnnotationTask = <ThrowOnError extends boolean = false>(
  options: Options<CompleteAnnotationTaskData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CompleteAnnotationTaskResponses,
    CompleteAnnotationTaskErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/{annotation_task_id}/annotate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Validate Annotation Submission
 *
 * Check whether ``label_id`` agrees with the KNN-majority prediction
 * derived from the task's satellite embedding and its nearest neighbours
 * in the same campaign.
 *
 * Always returns 200 with a ``status`` field indicating the outcome:
 * - ``ok``  – label matches neighbours
 * - ``mismatch`` – label disagrees with neighbours
 * - ``skipped_no_embedding`` – no embedding for the task
 * - ``skipped_insufficient_data`` – not enough labeled data yet
 * - ``disabled`` – no embedding year configured for this campaign
 */
export const validateAnnotationSubmission = <ThrowOnError extends boolean = false>(
  options: Options<ValidateAnnotationSubmissionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ValidateAnnotationSubmissionResponses,
    ValidateAnnotationSubmissionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_task_id}/validate-submission',
    ...options,
  });

/**
 * Ingest Annotation Tasks From Csv
 */
export const ingestAnnotationTasksFromCsv = <ThrowOnError extends boolean = false>(
  options: Options<IngestAnnotationTasksFromCsvData, ThrowOnError>
) =>
  (options.client ?? client).post<
    IngestAnnotationTasksFromCsvResponses,
    IngestAnnotationTasksFromCsvErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/ingest-annotation-task-csv',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Annotation Openmode
 */
export const createAnnotationOpenmode = <ThrowOnError extends boolean = false>(
  options: Options<CreateAnnotationOpenmodeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateAnnotationOpenmodeResponses,
    CreateAnnotationOpenmodeErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/create-annotation',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Annotation Openmode
 */
export const updateAnnotationOpenmode = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAnnotationOpenmodeData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateAnnotationOpenmodeResponses,
    UpdateAnnotationOpenmodeErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Annotation
 *
 * Delete a specific annotation from a campaign.
 *
 * If the annotation is linked to a task, the task status will be reset to pending.
 */
export const deleteAnnotation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnnotationData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAnnotationResponses,
    DeleteAnnotationErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}',
    ...options,
  });

/**
 * Export Annotations
 */
export const exportAnnotations = <ThrowOnError extends boolean = false>(
  options: Options<ExportAnnotationsData, ThrowOnError>
) =>
  (options.client ?? client).get<ExportAnnotationsResponses, ExportAnnotationsErrors, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/campaigns/{campaign_id}/export-annotations',
      ...options,
    }
  );

/**
 * Export Annotations Geojson
 *
 * Export all annotations for a campaign as a GeoJSON FeatureCollection file.
 */
export const exportAnnotationsGeojson = <ThrowOnError extends boolean = false>(
  options: Options<ExportAnnotationsGeojsonData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ExportAnnotationsGeojsonResponses,
    ExportAnnotationsGeojsonErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/export-annotations-geojson',
    ...options,
  });

/**
 * Get All Annotations For Campaign
 */
export const getAllAnnotationsForCampaign = <ThrowOnError extends boolean = false>(
  options: Options<GetAllAnnotationsForCampaignData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAllAnnotationsForCampaignResponses,
    GetAllAnnotationsForCampaignErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/annotations',
    ...options,
  });

/**
 * Get Timeseries For Campaign
 *
 * Get all timeseries configurations for a campaign. NOT the actual data, just the metadata about the timeseries.
 */
export const getTimeseriesForCampaign = <ThrowOnError extends boolean = false>(
  options: Options<GetTimeseriesForCampaignData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTimeseriesForCampaignResponses,
    GetTimeseriesForCampaignErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/timeseries',
    ...options,
  });

/**
 * Create Timeseries For Campaign
 *
 * Bulk create timeseries items for a campaign. Will register the timeseries configuration to campaign.
 */
export const createTimeseriesForCampaign = <ThrowOnError extends boolean = false>(
  options: Options<CreateTimeseriesForCampaignData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTimeseriesForCampaignResponses,
    CreateTimeseriesForCampaignErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/timeseries',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Timeseries Creation Options
 *
 * Get options for registering new timeseries for a campaign, such as supported data sources, providers, and types.
 */
export const getTimeseriesCreationOptions = <ThrowOnError extends boolean = false>(
  options?: Options<GetTimeseriesCreationOptionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetTimeseriesCreationOptionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/timeseries/create-options',
    ...options,
  });

/**
 * Get Timeseries Data
 *
 * Fetch the actual timeseries data from an external provider based on the timeseries config.
 */
export const getTimeseriesData = <ThrowOnError extends boolean = false>(
  options: Options<GetTimeseriesDataData, ThrowOnError>
) =>
  (options.client ?? client).get<GetTimeseriesDataResponses, GetTimeseriesDataErrors, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/timeseries/{timeseries_id}/{latitude}/{longitude}/data',
      ...options,
    }
  );

/**
 * Delete Timeseries
 *
 * Delete a timeseries. If it's the last one, removes it from all layouts.
 */
export const deleteTimeseries = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTimeseriesData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTimeseriesResponses,
    DeleteTimeseriesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/timeseries/{timeseries_id}',
    ...options,
  });

/**
 * Generate Tasks From Sampling
 *
 * Generate annotation tasks using a sampling strategy.
 *
 * You can either upload a region boundary file OR use the campaign's bounding box:
 *
 * **Option 1: Upload a region boundary file**
 * - `.zip` - Shapefile (containing .shp, .shx, .dbf, .prj files)
 * - `.geojson` or `.json` - GeoJSON file
 *
 * **Option 2: Use campaign bounding box**
 * - Set `use_campaign_bbox: true` in the strategy JSON
 * - No region_file required
 *
 * **Parameters:**
 * - strategy: JSON string with strategy_type, num_samples, use_campaign_bbox, and optional parameters
 * Example with file: {"strategy_type":"random","num_samples":10,"use_campaign_bbox":false,"parameters":{"seed":42}}
 * Example with bbox: {"strategy_type":"random","num_samples":10,"use_campaign_bbox":true,"parameters":{"seed":42}}
 *
 * Shapefiles will be automatically converted to EPSG:4326 if needed.
 * GeoJSON files are assumed to be in WGS84 (EPSG:4326) per specification.
 * Sample points will be generated within the boundary and created as annotation tasks.
 */
export const generateTasksFromSampling = <ThrowOnError extends boolean = false>(
  options: Options<GenerateTasksFromSamplingData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GenerateTasksFromSamplingResponses,
    GenerateTasksFromSamplingErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/campaigns/{campaign_id}/sampling/generate-tasks',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Imagery
 */
export const createImagery = <ThrowOnError extends boolean = false>(
  options: Options<CreateImageryData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateImageryResponses, CreateImageryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/{campaign_id}/imagery',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Imagery
 *
 * Delete an imagery entry and all associated data.
 */
export const deleteImagery = <ThrowOnError extends boolean = false>(
  options: Options<DeleteImageryData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteImageryResponses, DeleteImageryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/{campaign_id}/imagery/{imagery_id}',
    ...options,
  });

/**
 * Update Imagery
 *
 * Update an imagery configuration.
 * Excludes temporal fields (start_ym, end_ym, window_*, slicing_*) which cannot be changed currently.
 * TODO implement allowing to change temporal fields but needs handling of windows.
 */
export const updateImagery = <ThrowOnError extends boolean = false>(
  options: Options<UpdateImageryData, ThrowOnError>
) =>
  (options.client ?? client).patch<UpdateImageryResponses, UpdateImageryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/{campaign_id}/imagery/{imagery_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create New Canvas Layout For Imagery
 *
 * Create or update canvas layout for imagery visualization.
 *
 * If should_be_default is True, requires campaign admin role and updates
 * the default campaign-wide layout. Otherwise, creates/updates a personal
 * layout for the authenticated user.
 */
export const createNewCanvasLayoutForImagery = <ThrowOnError extends boolean = false>(
  options: Options<CreateNewCanvasLayoutForImageryData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNewCanvasLayoutForImageryResponses,
    CreateNewCanvasLayoutForImageryErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/{campaign_id}/new-layout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
