// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnnotationCreate
 */
export type AnnotationCreate = {
    /**
     * Label Id
     */
    label_id: number;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Geometry Wkt
     */
    geometry_wkt: string;
    /**
     * Confidence
     */
    confidence: number | null;
};

/**
 * AnnotationFromTaskCreate
 */
export type AnnotationFromTaskCreate = {
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Confidence
     */
    confidence: number | null;
    /**
     * Is Authoritative
     */
    is_authoritative?: boolean | null;
};

/**
 * AnnotationFromTaskOut
 */
export type AnnotationFromTaskOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created By User Id
     */
    created_by_user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Confidence
     */
    confidence: number | null;
    /**
     * Is Authoritative
     */
    is_authoritative: boolean;
};

/**
 * AnnotationOut
 */
export type AnnotationOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created By User Id
     */
    created_by_user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Confidence
     */
    confidence: number | null;
    /**
     * Is Authoritative
     */
    is_authoritative: boolean;
    geometry: GeometryOut;
};

/**
 * AnnotationTaskAssignmentOut
 */
export type AnnotationTaskAssignmentOut = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * User Email
     */
    user_email?: string | null;
    /**
     * User Display Name
     */
    user_display_name?: string | null;
};

/**
 * AnnotationTaskListOut
 */
export type AnnotationTaskListOut = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Tasks
     */
    tasks: Array<AnnotationTaskOut>;
};

/**
 * AnnotationTaskOut
 */
export type AnnotationTaskOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Annotation Number
     */
    annotation_number: number;
    /**
     * Task Status
     */
    task_status?: string;
    geometry: GeometryOut;
    /**
     * Assignments
     */
    assignments: Array<AnnotationTaskAssignmentOut> | null;
    /**
     * Annotations
     */
    annotations: Array<AnnotationFromTaskOut>;
};

/**
 * AnnotationTaskSubmitResponse
 *
 * Response from submitting/skipping an annotation task.
 */
export type AnnotationTaskSubmitResponse = {
    annotation: AnnotationFromTaskOut | null;
    /**
     * Task Status
     */
    task_status: string;
    /**
     * Assignment Status
     */
    assignment_status: string;
};

/**
 * AnnotationUpdate
 */
export type AnnotationUpdate = {
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Geometry Wkt
     */
    geometry_wkt: string | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Is Authoritative
     */
    is_authoritative: boolean | null;
};

/**
 * AnnotatorInfo
 *
 * Basic information about an annotator.
 */
export type AnnotatorInfo = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * User Email
     */
    user_email: string;
    /**
     * User Display Name
     */
    user_display_name: string | null;
    /**
     * Total Annotations
     */
    total_annotations: number;
    /**
     * Label Distribution
     */
    label_distribution: {
        [key: string]: number;
    };
};

/**
 * AssetInfo
 */
export type AssetInfo = {
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type: string;
    /**
     * Roles
     */
    roles: Array<string>;
};

/**
 * AssignReviewersRequest
 *
 * Request to assign reviewers to tasks based on different patterns.
 */
export type AssignReviewersRequest = {
    /**
     * Pattern
     */
    pattern: string;
    /**
     * Percentage
     */
    percentage?: number | null;
    /**
     * Num Reviewers
     */
    num_reviewers?: number | null;
    /**
     * Reviewer Ids
     */
    reviewer_ids?: Array<string> | null;
    /**
     * Manual Assignments
     */
    manual_assignments?: {
        [key: string]: Array<string>;
    } | null;
    /**
     * Num Tasks
     */
    num_tasks?: number | null;
    /**
     * Fixed Num Reviewers
     */
    fixed_num_reviewers?: number | null;
};

/**
 * AssignTasksToUsersRequest
 *
 * Request to assign multiple tasks to users.
 * Maps task IDs to list of user IDs (supports multiple reviewers per task).
 */
export type AssignTasksToUsersRequest = {
    /**
     * Task Assignments
     */
    task_assignments: {
        [key: string]: Array<string>;
    };
};

/**
 * AssignUsersToCampaignRequest
 */
export type AssignUsersToCampaignRequest = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * BasemapCreate
 */
export type BasemapCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
};

/**
 * BasemapOut
 */
export type BasemapOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
};

/**
 * Body_generateTasksFromSampling
 */
export type BodyGenerateTasksFromSampling = {
    /**
     * Strategy
     *
     * JSON string of SamplingStrategyConfig
     */
    strategy: string;
    /**
     * Region File
     *
     * Region boundary file (.zip shapefile or .geojson). Optional if using campaign bbox.
     */
    region_file?: string | null;
};

/**
 * Body_ingestAnnotationTasksFromCsv
 */
export type BodyIngestAnnotationTasksFromCsv = {
    /**
     * File
     */
    file: string;
};

/**
 * Body_ingestAnnotationTasksFromGeojson
 */
export type BodyIngestAnnotationTasksFromGeojson = {
    /**
     * File
     */
    file: string;
};

/**
 * BulkUserActionRequest
 *
 * Request body for bulk user operations.
 */
export type BulkUserActionRequest = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * BulkUserActionResponse
 *
 * Response for bulk user operations.
 */
export type BulkUserActionResponse = {
    /**
     * Success
     */
    success: Array<UserOutDetailed>;
    /**
     * Not Found
     */
    not_found: Array<string>;
    /**
     * Already In State
     */
    already_in_state: Array<UserOutDetailed>;
};

/**
 * CampaignCreate
 */
export type CampaignCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Is Public
     */
    is_public?: boolean;
    settings: CampaignSettingsCreate;
    imagery_editor_state?: ImageryEditorStateCreate | null;
    /**
     * Timeseries Configs
     */
    timeseries_configs?: Array<TimeSeriesCreate> | null;
};

/**
 * CampaignListItemOut
 */
export type CampaignListItemOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
    /**
     * Is Member
     */
    is_member?: boolean;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Registration Status
     */
    registration_status?: string;
    /**
     * Embedding Status
     */
    embedding_status?: string;
};

/**
 * CampaignOut
 */
export type CampaignOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Registration Status
     */
    registration_status?: string;
    /**
     * Embedding Status
     */
    embedding_status?: string;
    /**
     * Registration Errors
     */
    registration_errors?: Array<{
        [key: string]: unknown;
    }> | null;
    settings: CampaignSettingsOut;
    /**
     * Imagery Sources
     */
    imagery_sources: Array<ImagerySourceOut>;
    /**
     * Imagery Views
     */
    imagery_views: Array<ImageryViewOut>;
    /**
     * Basemaps
     */
    basemaps: Array<BasemapOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
};

/**
 * CampaignOutFull
 *
 * Campaign with canvas layout information extracted.
 */
export type CampaignOutFull = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Registration Status
     */
    registration_status?: string;
    /**
     * Embedding Status
     */
    embedding_status?: string;
    /**
     * Registration Errors
     */
    registration_errors?: Array<{
        [key: string]: unknown;
    }> | null;
    settings: CampaignSettingsOut;
    /**
     * Imagery Sources
     */
    imagery_sources: Array<ImagerySourceOut>;
    /**
     * Imagery Views
     */
    imagery_views: Array<ImageryViewOut>;
    /**
     * Basemaps
     */
    basemaps: Array<BasemapOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
    readonly default_main_canvas_layout: CanvasLayoutOut | null;
    readonly personal_main_canvas_layout: CanvasLayoutOut | null;
};

/**
 * CampaignSettingsCreate
 */
export type CampaignSettingsCreate = {
    /**
     * Labels
     */
    labels: Array<LabelBase>;
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
    /**
     * Embedding Year
     */
    embedding_year?: number | null;
    /**
     * Sample Extent Meters
     */
    sample_extent_meters?: number | null;
};

/**
 * CampaignSettingsOut
 */
export type CampaignSettingsOut = {
    /**
     * Labels
     */
    labels: Array<LabelBase>;
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
    /**
     * Embedding Year
     */
    embedding_year?: number | null;
    /**
     * Guide Markdown
     */
    guide_markdown?: string | null;
    /**
     * Sample Extent Meters
     */
    sample_extent_meters?: number | null;
};

/**
 * CampaignStatistics
 *
 * Statistics for a campaign focused on inter-annotator agreement.
 */
export type CampaignStatistics = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Campaign Name
     */
    campaign_name: string;
    /**
     * Total Annotations
     */
    total_annotations: number;
    /**
     * Tasks With Multiple Annotations
     */
    tasks_with_multiple_annotations: number;
    /**
     * Overall Label Distribution
     */
    overall_label_distribution: {
        [key: string]: number;
    };
    /**
     * Krippendorff Alpha
     */
    krippendorff_alpha: number | null;
    /**
     * Annotators
     */
    annotators: Array<AnnotatorInfo>;
    /**
     * Pairwise Agreements
     */
    pairwise_agreements: Array<PairwiseAgreement>;
};

/**
 * CampaignUserOut
 */
export type CampaignUserOut = {
    user: UserOut;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Is Authorative Reviewer
     */
    is_authorative_reviewer: boolean;
};

/**
 * CampaignUsersResponse
 */
export type CampaignUsersResponse = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Users
     */
    users: Array<CampaignUserOut>;
};

/**
 * CampaignsListResponse
 */
export type CampaignsListResponse = {
    /**
     * Items
     */
    items: Array<CampaignListItemOut>;
};

/**
 * CanvasLayoutCreate
 */
export type CanvasLayoutCreate = {
    /**
     * Main Layout Data
     */
    main_layout_data: Array<unknown>;
    /**
     * View Layout Data
     */
    view_layout_data?: Array<unknown> | null;
    /**
     * View Id
     */
    view_id?: number | null;
};

/**
 * CanvasLayoutCreateRequest
 */
export type CanvasLayoutCreateRequest = {
    layout: CanvasLayoutCreate;
    /**
     * Should Be Default
     */
    should_be_default?: boolean;
    /**
     * View Id
     */
    view_id: number;
};

/**
 * CanvasLayoutOut
 */
export type CanvasLayoutOut = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Layout Data
     */
    layout_data: Array<unknown>;
};

/**
 * CollectionStacConfigCreate
 */
export type CollectionStacConfigCreate = {
    /**
     * Registration Url
     */
    registration_url?: string;
    /**
     * Search Body
     */
    search_body?: string;
    /**
     * Catalog Url
     */
    catalog_url?: string | null;
    /**
     * Stac Collection Id
     */
    stac_collection_id?: string | null;
    viz_params?: VizParamsCreate | null;
    cover_viz_params?: VizParamsCreate | null;
    /**
     * Max Cloud Cover
     */
    max_cloud_cover?: number | null;
    /**
     * Search Query
     */
    search_query?: {
        [key: string]: unknown;
    } | null;
    /**
     * Cover Search Query
     */
    cover_search_query?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CollectionStacConfigOut
 */
export type CollectionStacConfigOut = {
    /**
     * Registration Url
     */
    registration_url: string;
    /**
     * Search Body
     */
    search_body: string;
    /**
     * Catalog Url
     */
    catalog_url?: string | null;
    /**
     * Stac Collection Id
     */
    stac_collection_id?: string | null;
    /**
     * Viz Params
     */
    viz_params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Cover Viz Params
     */
    cover_viz_params?: {
        [key: string]: unknown;
    } | null;
    /**
     * Max Cloud Cover
     */
    max_cloud_cover?: number | null;
    /**
     * Search Query
     */
    search_query?: {
        [key: string]: unknown;
    } | null;
    /**
     * Cover Search Query
     */
    cover_search_query?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DeleteAnnotationTasksRequest
 *
 * Request to delete multiple annotation tasks.
 */
export type DeleteAnnotationTasksRequest = {
    /**
     * Task Ids
     */
    task_ids: Array<number>;
};

/**
 * EmbeddingYearUpdateResponse
 *
 * Response after updating the embedding year.
 * Includes a summary of re-computation if embeddings were regenerated.
 */
export type EmbeddingYearUpdateResponse = {
    /**
     * Embedding Year
     */
    embedding_year: number | null;
    /**
     * Embeddings Recomputed
     */
    embeddings_recomputed: boolean;
    /**
     * Summary
     */
    summary?: {
        [key: string]: unknown;
    } | null;
};

/**
 * GenerateTasksResponse
 *
 * Response after generating tasks.
 */
export type GenerateTasksResponse = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Num Tasks Created
     */
    num_tasks_created: number;
    /**
     * Message
     */
    message: string;
};

/**
 * GeometryOut
 */
export type GeometryOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Geometry
     */
    geometry: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageryCollectionCreate
 */
export type ImageryCollectionCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Cover Slice Index
     */
    cover_slice_index?: number;
    /**
     * Slices
     */
    slices: Array<ImagerySliceCreate>;
    stac_config?: CollectionStacConfigCreate | null;
};

/**
 * ImageryCollectionOut
 */
export type ImageryCollectionOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Cover Slice Index
     */
    cover_slice_index: number;
    /**
     * Display Order
     */
    display_order: number;
    /**
     * Slices
     */
    slices: Array<ImagerySliceOut>;
    stac_config?: CollectionStacConfigOut | null;
};

/**
 * ImageryCollectionUpdate
 *
 * Partial update for an imagery collection.
 */
export type ImageryCollectionUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Cover Slice Index
     */
    cover_slice_index?: number | null;
};

/**
 * ImageryEditorStateCreate
 *
 * Full imagery editor state sent from the frontend on campaign creation.
 */
export type ImageryEditorStateCreate = {
    /**
     * Sources
     */
    sources: Array<ImagerySourceCreate>;
    /**
     * Views
     */
    views: Array<ImageryViewCreate>;
    /**
     * Basemaps
     */
    basemaps: Array<BasemapCreate>;
};

/**
 * ImagerySliceCreate
 */
export type ImagerySliceCreate = {
    /**
     * Name
     */
    name?: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Tile Urls
     */
    tile_urls?: Array<SliceTileUrlCreate>;
};

/**
 * ImagerySliceOut
 */
export type ImagerySliceOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Display Order
     */
    display_order: number;
    /**
     * Tile Urls
     */
    tile_urls: Array<SliceTileUrlOut>;
};

/**
 * ImagerySourceCreate
 */
export type ImagerySourceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6?: string;
    /**
     * Default Zoom
     */
    default_zoom?: number;
    /**
     * Visualizations
     */
    visualizations: Array<VisualizationTemplateCreate>;
    /**
     * Collections
     */
    collections: Array<ImageryCollectionCreate>;
};

/**
 * ImagerySourceOut
 */
export type ImagerySourceOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6: string;
    /**
     * Default Zoom
     */
    default_zoom: number;
    /**
     * Display Order
     */
    display_order: number;
    /**
     * Visualizations
     */
    visualizations: Array<VisualizationTemplateOut>;
    /**
     * Collections
     */
    collections: Array<ImageryCollectionOut>;
};

/**
 * ImagerySourceUpdate
 *
 * Partial update for an imagery source's display settings.
 */
export type ImagerySourceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6?: string | null;
    /**
     * Default Zoom
     */
    default_zoom?: number | null;
    /**
     * Visualizations
     */
    visualizations?: Array<VisualizationUpdate> | null;
};

/**
 * ImageryViewAddRequest
 *
 * Create a new view on an existing campaign.
 */
export type ImageryViewAddRequest = {
    /**
     * Name
     */
    name?: string;
    /**
     * Collection Refs
     */
    collection_refs?: Array<ViewCollectionRefItem>;
};

/**
 * ImageryViewCreate
 */
export type ImageryViewCreate = {
    /**
     * Name
     */
    name?: string;
    /**
     * Collection Refs
     */
    collection_refs?: Array<ViewCollectionRefCreate>;
};

/**
 * ImageryViewOut
 */
export type ImageryViewOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Display Order
     */
    display_order: number;
    /**
     * Collection Refs
     */
    collection_refs: Array<ViewCollectionRefItem>;
    readonly default_canvas_layout: CanvasLayoutOut | null;
    readonly personal_canvas_layout: CanvasLayoutOut | null;
};

/**
 * ImageryViewUpdate
 *
 * Partial update for an imagery view.
 */
export type ImageryViewUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Display Order
     */
    display_order?: number | null;
    /**
     * Collection Refs
     */
    collection_refs?: Array<ViewCollectionRefItem> | null;
};

/**
 * LabelBase
 *
 * A label that can be assigned to an annotation within a campaign.
 */
export type LabelBase = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Geometry Type
     */
    geometry_type?: 'point' | 'polygon' | 'line' | null;
};

/**
 * MosaicRegisterRequest
 */
export type MosaicRegisterRequest = {
    /**
     * Catalog Url
     */
    catalog_url: string;
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Bbox
     */
    bbox: Array<number>;
    /**
     * Datetime Range
     */
    datetime_range: string;
    /**
     * Max Items
     */
    max_items?: number | null;
};

/**
 * MosaicRegisterResponse
 */
export type MosaicRegisterResponse = {
    /**
     * Mosaic Id
     */
    mosaic_id: string;
    /**
     * Item Count
     */
    item_count: number;
    /**
     * Assets
     */
    assets: {
        [key: string]: AssetInfo;
    };
};

/**
 * PairwiseAgreement
 *
 * Agreement percentage between two annotators.
 */
export type PairwiseAgreement = {
    /**
     * Annotator1 Id
     */
    annotator1_id: string;
    /**
     * Annotator2 Id
     */
    annotator2_id: string;
    /**
     * Agreement Percentage
     */
    agreement_percentage: number | null;
    /**
     * Shared Tasks
     */
    shared_tasks: number;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Catalog Url
     */
    catalog_url: string;
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Bbox
     */
    bbox?: Array<number> | null;
    /**
     * Datetime Range
     */
    datetime_range?: string | null;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * SearchResponse
 */
export type SearchResponse = {
    /**
     * Items
     */
    items: Array<StacItemOut>;
    /**
     * Count
     */
    count: number;
};

/**
 * SliceTileUrlCreate
 */
export type SliceTileUrlCreate = {
    /**
     * Visualization Name
     */
    visualization_name: string;
    /**
     * Tile Url
     */
    tile_url: string;
};

/**
 * SliceTileUrlOut
 */
export type SliceTileUrlOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Visualization Name
     */
    visualization_name: string;
    /**
     * Tile Url
     */
    tile_url: string;
    /**
     * Tile Provider
     */
    tile_provider?: string | null;
    /**
     * Mosaic Id
     */
    mosaic_id?: string | null;
    /**
     * Mosaic Status
     */
    mosaic_status?: string | null;
    /**
     * Registered At
     */
    registered_at?: string | null;
};

/**
 * StacItemOut
 */
export type StacItemOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Datetime
     */
    datetime?: string | null;
    /**
     * Bbox
     */
    bbox?: Array<number> | null;
    /**
     * Geometry
     */
    geometry?: {
        [key: string]: unknown;
    } | null;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    };
    /**
     * Assets
     */
    assets?: {
        [key: string]: AssetInfo;
    };
    /**
     * Thumbnail
     */
    thumbnail?: string | null;
    /**
     * Self Href
     */
    self_href?: string | null;
};

/**
 * TimeSeriesCreate
 */
export type TimeSeriesCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Ts Type
     */
    ts_type: string;
};

/**
 * TimeSeriesOptionsOut
 */
export type TimeSeriesOptionsOut = {
    /**
     * Data Sources
     */
    data_sources: Array<string>;
    /**
     * Providers
     */
    providers: Array<string>;
    /**
     * Ts Types
     */
    ts_types: Array<string>;
};

/**
 * TimeSeriesOut
 */
export type TimeSeriesOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Ts Type
     */
    ts_type: string;
    /**
     * Id
     */
    id: number;
    /**
     * Campaign Id
     */
    campaign_id: number;
};

/**
 * TimeseriesBulkCreateRequest
 */
export type TimeseriesBulkCreateRequest = {
    /**
     * Timeseries
     */
    timeseries: Array<TimeSeriesCreate>;
};

/**
 * TimeseriesBulkCreateResponse
 */
export type TimeseriesBulkCreateResponse = {
    /**
     * New Items
     */
    new_items: Array<TimeSeriesOut>;
};

/**
 * TimeseriesDataResponse
 */
export type TimeseriesDataResponse = {
    /**
     * Timeseries Id
     */
    timeseries_id: number;
    /**
     * Data
     */
    data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TimeseriesListResponse
 */
export type TimeseriesListResponse = {
    /**
     * Items
     */
    items: Array<TimeSeriesOut>;
};

/**
 * UpdateCampaignBBoxRequest
 */
export type UpdateCampaignBBoxRequest = {
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
};

/**
 * UpdateCampaignGuideRequest
 */
export type UpdateCampaignGuideRequest = {
    /**
     * Guide Markdown
     */
    guide_markdown?: string | null;
};

/**
 * UpdateCampaignNameRequest
 */
export type UpdateCampaignNameRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * UpdateCampaignVisibilityRequest
 */
export type UpdateCampaignVisibilityRequest = {
    /**
     * Is Public
     */
    is_public: boolean;
};

/**
 * UpdateEmbeddingYearRequest
 *
 * Set or change the year from which satellite embeddings are sourced.
 */
export type UpdateEmbeddingYearRequest = {
    /**
     * Embedding Year
     */
    embedding_year?: number | null;
};

/**
 * UpdateSampleExtentRequest
 */
export type UpdateSampleExtentRequest = {
    /**
     * Sample Extent Meters
     */
    sample_extent_meters?: number | null;
};

/**
 * UserOut
 *
 * Basic user information.
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * UserOutDetailed
 *
 * Detailed user information.
 */
export type UserOutDetailed = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Approved
     */
    is_approved: boolean;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Issuer
     */
    issuer: string;
    /**
     * External Uid
     */
    external_uid: string;
};

/**
 * ValidateLabelSubmissionsResponse
 *
 * Result of a KNN-based label validation check.
 *
 * status tells the caller why a certain result was returned:
 *
 * - "ok" - enough data, label agrees with neighbours
 * - "mismatch" - enough data, label disagrees with neighbours
 * - "skipped_no_embedding" - task has no embedding vector
 * - "skipped_insufficient_data" - not enough labeled neighbours yet
 * - "disabled" - validation is disabled (no embedding year configured)
 */
export type ValidateLabelSubmissionsResponse = {
    /**
     * Status
     */
    status: 'ok' | 'mismatch' | 'skipped_no_embedding' | 'skipped_insufficient_data' | 'disabled';
    /**
     * Agrees
     */
    agrees?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ViewCollectionRefCreate
 */
export type ViewCollectionRefCreate = {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Show As Window
     */
    show_as_window?: boolean;
};

/**
 * ViewCollectionRefItem
 */
export type ViewCollectionRefItem = {
    /**
     * Collection Id
     */
    collection_id: number;
    /**
     * Source Id
     */
    source_id: number;
    /**
     * Show As Window
     */
    show_as_window?: boolean;
};

/**
 * VisualizationTemplateCreate
 */
export type VisualizationTemplateCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * VisualizationTemplateOut
 */
export type VisualizationTemplateOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Display Order
     */
    display_order: number;
};

/**
 * VisualizationUpdate
 */
export type VisualizationUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * VizParamsCreate
 *
 * Structured visualization parameters for TiTiler tile rendering.
 */
export type VizParamsCreate = {
    /**
     * Assets
     */
    assets?: Array<string>;
    /**
     * Asset As Band
     */
    asset_as_band?: boolean;
    /**
     * Rescale
     */
    rescale?: string | null;
    /**
     * Colormap Name
     */
    colormap_name?: string | null;
    /**
     * Color Formula
     */
    color_formula?: string | null;
    /**
     * Expression
     */
    expression?: string | null;
    /**
     * Resampling
     */
    resampling?: string | null;
    /**
     * Compositing
     */
    compositing?: string | null;
    /**
     * Nodata
     */
    nodata?: number | null;
    /**
     * Extra Params
     */
    extra_params?: {
        [key: string]: string;
    } | null;
    /**
     * Mask Layer
     */
    mask_layer?: string | null;
    /**
     * Mask Values
     */
    mask_values?: Array<number> | null;
    /**
     * Nir Band
     */
    nir_band?: string | null;
    /**
     * Red Band
     */
    red_band?: string | null;
    /**
     * Max Items
     */
    max_items?: number | null;
};

/**
 * CampaignOut
 */
export type CampaignOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Registration Status
     */
    registration_status?: string;
    /**
     * Embedding Status
     */
    embedding_status?: string;
    /**
     * Registration Errors
     */
    registration_errors?: Array<{
        [key: string]: unknown;
    }> | null;
    settings: CampaignSettingsOut;
    /**
     * Imagery Sources
     */
    imagery_sources: Array<ImagerySourceOut>;
    /**
     * Imagery Views
     */
    imagery_views: Array<ImageryViewOutWritable>;
    /**
     * Basemaps
     */
    basemaps: Array<BasemapOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
};

/**
 * CampaignOutFull
 *
 * Campaign with canvas layout information extracted.
 */
export type CampaignOutFullWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Registration Status
     */
    registration_status?: string;
    /**
     * Embedding Status
     */
    embedding_status?: string;
    /**
     * Registration Errors
     */
    registration_errors?: Array<{
        [key: string]: unknown;
    }> | null;
    settings: CampaignSettingsOut;
    /**
     * Imagery Sources
     */
    imagery_sources: Array<ImagerySourceOut>;
    /**
     * Imagery Views
     */
    imagery_views: Array<ImageryViewOutWritable>;
    /**
     * Basemaps
     */
    basemaps: Array<BasemapOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
};

/**
 * ImageryViewOut
 */
export type ImageryViewOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Display Order
     */
    display_order: number;
    /**
     * Collection Refs
     */
    collection_refs: Array<ViewCollectionRefItem>;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type GetTilerTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/tiler-token';
};

export type GetTilerTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users';
};

export type ListUsersResponses = {
    /**
     * Response Listusers
     *
     * Successful Response
     */
    200: Array<UserOutDetailed>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type EditUserInfoData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query: {
        /**
         * New Display Name
         */
        new_display_name: string;
    };
    url: '/api/auth/users/{user_id}';
};

export type EditUserInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditUserInfoError = EditUserInfoErrors[keyof EditUserInfoErrors];

export type EditUserInfoResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type EditUserInfoResponse = EditUserInfoResponses[keyof EditUserInfoResponses];

export type ApproveUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/approve';
};

export type ApproveUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveUserError = ApproveUserErrors[keyof ApproveUserErrors];

export type ApproveUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type ApproveUserResponse = ApproveUserResponses[keyof ApproveUserResponses];

export type RevokeUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/revoke';
};

export type RevokeUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeUserError = RevokeUserErrors[keyof RevokeUserErrors];

export type RevokeUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type RevokeUserResponse = RevokeUserResponses[keyof RevokeUserResponses];

export type DenyUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/deny';
};

export type DenyUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DenyUserError = DenyUserErrors[keyof DenyUserErrors];

export type DenyUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type DenyUserResponse = DenyUserResponses[keyof DenyUserResponses];

export type ApproveUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/approve';
};

export type ApproveUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveUsersBulkError = ApproveUsersBulkErrors[keyof ApproveUsersBulkErrors];

export type ApproveUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type ApproveUsersBulkResponse = ApproveUsersBulkResponses[keyof ApproveUsersBulkResponses];

export type RevokeUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/revoke';
};

export type RevokeUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeUsersBulkError = RevokeUsersBulkErrors[keyof RevokeUsersBulkErrors];

export type RevokeUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type RevokeUsersBulkResponse = RevokeUsersBulkResponses[keyof RevokeUsersBulkResponses];

export type DenyUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/deny';
};

export type DenyUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DenyUsersBulkError = DenyUsersBulkErrors[keyof DenyUsersBulkErrors];

export type DenyUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type DenyUsersBulkResponse = DenyUsersBulkResponses[keyof DenyUsersBulkResponses];

export type GrantAdminSingleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/grant-admin';
};

export type GrantAdminSingleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantAdminSingleError = GrantAdminSingleErrors[keyof GrantAdminSingleErrors];

export type GrantAdminSingleResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type GrantAdminSingleResponse = GrantAdminSingleResponses[keyof GrantAdminSingleResponses];

export type RevokeAdminSingleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/revoke-admin';
};

export type RevokeAdminSingleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAdminSingleError = RevokeAdminSingleErrors[keyof RevokeAdminSingleErrors];

export type RevokeAdminSingleResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type RevokeAdminSingleResponse = RevokeAdminSingleResponses[keyof RevokeAdminSingleResponses];

export type GrantAdminData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/grant-admin';
};

export type GrantAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantAdminError = GrantAdminErrors[keyof GrantAdminErrors];

export type GrantAdminResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type GrantAdminResponse = GrantAdminResponses[keyof GrantAdminResponses];

export type RevokeAdminData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/revoke-admin';
};

export type RevokeAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAdminError = RevokeAdminErrors[keyof RevokeAdminErrors];

export type RevokeAdminResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type RevokeAdminResponse = RevokeAdminResponses[keyof RevokeAdminResponses];

export type ListAllCampaignsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/campaigns/';
};

export type ListAllCampaignsResponses = {
    /**
     * Successful Response
     */
    200: CampaignsListResponse;
};

export type ListAllCampaignsResponse = ListAllCampaignsResponses[keyof ListAllCampaignsResponses];

export type CreateCampaignData = {
    body: CampaignCreate;
    path?: never;
    query?: never;
    url: '/api/campaigns/';
};

export type CreateCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCampaignError = CreateCampaignErrors[keyof CreateCampaignErrors];

export type CreateCampaignResponses = {
    /**
     * Successful Response
     */
    201: CampaignOut;
};

export type CreateCampaignResponse = CreateCampaignResponses[keyof CreateCampaignResponses];

export type DeleteCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}';
};

export type DeleteCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCampaignError = DeleteCampaignErrors[keyof DeleteCampaignErrors];

export type DeleteCampaignResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCampaignResponse = DeleteCampaignResponses[keyof DeleteCampaignResponses];

export type GetCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}';
};

export type GetCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignError = GetCampaignErrors[keyof GetCampaignErrors];

export type GetCampaignResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type GetCampaignResponse = GetCampaignResponses[keyof GetCampaignResponses];

export type AddUsersToCampaignData = {
    body: AssignUsersToCampaignRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/assign-users';
};

export type AddUsersToCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUsersToCampaignError = AddUsersToCampaignErrors[keyof AddUsersToCampaignErrors];

export type AddUsersToCampaignResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetCampaignWithImageryWindowsData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/detailed';
};

export type GetCampaignWithImageryWindowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignWithImageryWindowsError = GetCampaignWithImageryWindowsErrors[keyof GetCampaignWithImageryWindowsErrors];

export type GetCampaignWithImageryWindowsResponses = {
    /**
     * Successful Response
     */
    200: CampaignOutFull;
};

export type GetCampaignWithImageryWindowsResponse = GetCampaignWithImageryWindowsResponses[keyof GetCampaignWithImageryWindowsResponses];

export type MakeUserCampaignAdminData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * New Admin User Id
         */
        new_admin_user_id: string;
    };
    url: '/api/campaigns/{campaign_id}/make-user-admin';
};

export type MakeUserCampaignAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeUserCampaignAdminError = MakeUserCampaignAdminErrors[keyof MakeUserCampaignAdminErrors];

export type MakeUserCampaignAdminResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type MakeUserAuthorativeReviewerData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * New Authorative Reviewer Id
         */
        new_authorative_reviewer_id: string;
    };
    url: '/api/campaigns/{campaign_id}/make-user-authorative-reviewer';
};

export type MakeUserAuthorativeReviewerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeUserAuthorativeReviewerError = MakeUserAuthorativeReviewerErrors[keyof MakeUserAuthorativeReviewerErrors];

export type MakeUserAuthorativeReviewerResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetCampaignUsersData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/users';
};

export type GetCampaignUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignUsersError = GetCampaignUsersErrors[keyof GetCampaignUsersErrors];

export type GetCampaignUsersResponses = {
    /**
     * Successful Response
     */
    200: CampaignUsersResponse;
};

export type GetCampaignUsersResponse = GetCampaignUsersResponses[keyof GetCampaignUsersResponses];

export type UpdateCampaignNameData = {
    body: UpdateCampaignNameRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/name';
};

export type UpdateCampaignNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignNameError = UpdateCampaignNameErrors[keyof UpdateCampaignNameErrors];

export type UpdateCampaignNameResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignNameResponse = UpdateCampaignNameResponses[keyof UpdateCampaignNameResponses];

export type UpdateCampaignVisibilityData = {
    body: UpdateCampaignVisibilityRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/visibility';
};

export type UpdateCampaignVisibilityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignVisibilityError = UpdateCampaignVisibilityErrors[keyof UpdateCampaignVisibilityErrors];

export type UpdateCampaignVisibilityResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignVisibilityResponse = UpdateCampaignVisibilityResponses[keyof UpdateCampaignVisibilityResponses];

export type UpdateCampaignGuideData = {
    body: UpdateCampaignGuideRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/guide';
};

export type UpdateCampaignGuideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignGuideError = UpdateCampaignGuideErrors[keyof UpdateCampaignGuideErrors];

export type UpdateCampaignGuideResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignGuideResponse = UpdateCampaignGuideResponses[keyof UpdateCampaignGuideResponses];

export type UpdateCampaignBboxData = {
    body: UpdateCampaignBBoxRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/bbox';
};

export type UpdateCampaignBboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignBboxError = UpdateCampaignBboxErrors[keyof UpdateCampaignBboxErrors];

export type UpdateCampaignBboxResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignBboxResponse = UpdateCampaignBboxResponses[keyof UpdateCampaignBboxResponses];

export type UpdateSampleExtentData = {
    body: UpdateSampleExtentRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/sample-extent';
};

export type UpdateSampleExtentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSampleExtentError = UpdateSampleExtentErrors[keyof UpdateSampleExtentErrors];

export type UpdateSampleExtentResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateSampleExtentResponse = UpdateSampleExtentResponses[keyof UpdateSampleExtentResponses];

export type UpdateEmbeddingYearData = {
    body: UpdateEmbeddingYearRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/embedding-year';
};

export type UpdateEmbeddingYearErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEmbeddingYearError = UpdateEmbeddingYearErrors[keyof UpdateEmbeddingYearErrors];

export type UpdateEmbeddingYearResponses = {
    /**
     * Successful Response
     */
    200: EmbeddingYearUpdateResponse;
};

export type UpdateEmbeddingYearResponse = UpdateEmbeddingYearResponses[keyof UpdateEmbeddingYearResponses];

export type RemoveUserFromCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/users/{user_id}';
};

export type RemoveUserFromCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromCampaignError = RemoveUserFromCampaignErrors[keyof RemoveUserFromCampaignErrors];

export type RemoveUserFromCampaignResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveUserFromCampaignResponse = RemoveUserFromCampaignResponses[keyof RemoveUserFromCampaignResponses];

export type DemoteCampaignAdminData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/campaigns/{campaign_id}/demote-admin';
};

export type DemoteCampaignAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoteCampaignAdminError = DemoteCampaignAdminErrors[keyof DemoteCampaignAdminErrors];

export type DemoteCampaignAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DemoteAuthorativeReviewerData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/campaigns/{campaign_id}/demote-auth-reviewer';
};

export type DemoteAuthorativeReviewerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoteAuthorativeReviewerError = DemoteAuthorativeReviewerErrors[keyof DemoteAuthorativeReviewerErrors];

export type DemoteAuthorativeReviewerResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignTasksToUsersData = {
    body: AssignTasksToUsersRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/assign-tasks';
};

export type AssignTasksToUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignTasksToUsersError = AssignTasksToUsersErrors[keyof AssignTasksToUsersErrors];

export type AssignTasksToUsersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnassignUserFromTaskData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Task Id
         */
        task_id: number;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/tasks/{task_id}/unassign-user/{user_id}';
};

export type UnassignUserFromTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnassignUserFromTaskError = UnassignUserFromTaskErrors[keyof UnassignUserFromTaskErrors];

export type UnassignUserFromTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignReviewersData = {
    body: AssignReviewersRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/assign-reviewers';
};

export type AssignReviewersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignReviewersError = AssignReviewersErrors[keyof AssignReviewersErrors];

export type AssignReviewersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RemoveUserFromTaskData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Task Id
         */
        task_id: number;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/tasks/{task_id}/users/{user_id}';
};

export type RemoveUserFromTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromTaskError = RemoveUserFromTaskErrors[keyof RemoveUserFromTaskErrors];

export type RemoveUserFromTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAnnotationTasksData = {
    body: DeleteAnnotationTasksRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotation-tasks';
};

export type DeleteAnnotationTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnnotationTasksError = DeleteAnnotationTasksErrors[keyof DeleteAnnotationTasksErrors];

export type DeleteAnnotationTasksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllAnnotationTasksData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotation-tasks';
};

export type GetAllAnnotationTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAnnotationTasksError = GetAllAnnotationTasksErrors[keyof GetAllAnnotationTasksErrors];

export type GetAllAnnotationTasksResponses = {
    /**
     * Successful Response
     */
    200: AnnotationTaskListOut;
};

export type GetAllAnnotationTasksResponse = GetAllAnnotationTasksResponses[keyof GetAllAnnotationTasksResponses];

export type GetCampaignStatisticsEndpointData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/statistics';
};

export type GetCampaignStatisticsEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignStatisticsEndpointError = GetCampaignStatisticsEndpointErrors[keyof GetCampaignStatisticsEndpointErrors];

export type GetCampaignStatisticsEndpointResponses = {
    /**
     * Successful Response
     */
    200: CampaignStatistics;
};

export type GetCampaignStatisticsEndpointResponse = GetCampaignStatisticsEndpointResponses[keyof GetCampaignStatisticsEndpointResponses];

export type CompleteAnnotationTaskData = {
    body: AnnotationFromTaskCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Annotation Task Id
         */
        annotation_task_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/{annotation_task_id}/annotate';
};

export type CompleteAnnotationTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteAnnotationTaskError = CompleteAnnotationTaskErrors[keyof CompleteAnnotationTaskErrors];

export type CompleteAnnotationTaskResponses = {
    /**
     * Successful Response
     */
    200: AnnotationTaskSubmitResponse;
};

export type CompleteAnnotationTaskResponse = CompleteAnnotationTaskResponses[keyof CompleteAnnotationTaskResponses];

export type ValidateAnnotationSubmissionData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Annotation Task Id
         */
        annotation_task_id: number;
    };
    query: {
        /**
         * Label Id
         */
        label_id: number;
    };
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_task_id}/validate-submission';
};

export type ValidateAnnotationSubmissionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateAnnotationSubmissionError = ValidateAnnotationSubmissionErrors[keyof ValidateAnnotationSubmissionErrors];

export type ValidateAnnotationSubmissionResponses = {
    /**
     * Successful Response
     */
    200: ValidateLabelSubmissionsResponse;
};

export type ValidateAnnotationSubmissionResponse = ValidateAnnotationSubmissionResponses[keyof ValidateAnnotationSubmissionResponses];

export type IngestAnnotationTasksFromCsvData = {
    body: BodyIngestAnnotationTasksFromCsv;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/ingest-annotation-task-csv';
};

export type IngestAnnotationTasksFromCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestAnnotationTasksFromCsvError = IngestAnnotationTasksFromCsvErrors[keyof IngestAnnotationTasksFromCsvErrors];

export type IngestAnnotationTasksFromCsvResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IngestAnnotationTasksFromGeojsonData = {
    body: BodyIngestAnnotationTasksFromGeojson;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/ingest-annotation-task-geojson';
};

export type IngestAnnotationTasksFromGeojsonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestAnnotationTasksFromGeojsonError = IngestAnnotationTasksFromGeojsonErrors[keyof IngestAnnotationTasksFromGeojsonErrors];

export type IngestAnnotationTasksFromGeojsonResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateAnnotationOpenmodeData = {
    body: AnnotationCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/create-annotation';
};

export type CreateAnnotationOpenmodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnnotationOpenmodeError = CreateAnnotationOpenmodeErrors[keyof CreateAnnotationOpenmodeErrors];

export type CreateAnnotationOpenmodeResponses = {
    /**
     * Successful Response
     */
    200: AnnotationOut;
};

export type CreateAnnotationOpenmodeResponse = CreateAnnotationOpenmodeResponses[keyof CreateAnnotationOpenmodeResponses];

export type UpdateAnnotationOpenmodeData = {
    body: AnnotationUpdate;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}/update';
};

export type UpdateAnnotationOpenmodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnnotationOpenmodeError = UpdateAnnotationOpenmodeErrors[keyof UpdateAnnotationOpenmodeErrors];

export type UpdateAnnotationOpenmodeResponses = {
    /**
     * Successful Response
     */
    200: AnnotationOut;
};

export type UpdateAnnotationOpenmodeResponse = UpdateAnnotationOpenmodeResponses[keyof UpdateAnnotationOpenmodeResponses];

export type DeleteAnnotationData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}';
};

export type DeleteAnnotationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnnotationError = DeleteAnnotationErrors[keyof DeleteAnnotationErrors];

export type DeleteAnnotationResponses = {
    /**
     * Response Deleteannotation
     *
     * Successful Response
     */
    200: AnnotationTaskSubmitResponse | null;
};

export type DeleteAnnotationResponse = DeleteAnnotationResponses[keyof DeleteAnnotationResponses];

export type ExportAnnotationsData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/export-annotations';
};

export type ExportAnnotationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportAnnotationsError = ExportAnnotationsErrors[keyof ExportAnnotationsErrors];

export type ExportAnnotationsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportAnnotationsGeojsonData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/export-annotations-geojson';
};

export type ExportAnnotationsGeojsonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportAnnotationsGeojsonError = ExportAnnotationsGeojsonErrors[keyof ExportAnnotationsGeojsonErrors];

export type ExportAnnotationsGeojsonResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllAnnotationsForCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations';
};

export type GetAllAnnotationsForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAnnotationsForCampaignError = GetAllAnnotationsForCampaignErrors[keyof GetAllAnnotationsForCampaignErrors];

export type GetAllAnnotationsForCampaignResponses = {
    /**
     * Response Getallannotationsforcampaign
     *
     * Successful Response
     */
    200: Array<AnnotationOut>;
};

export type GetAllAnnotationsForCampaignResponse = GetAllAnnotationsForCampaignResponses[keyof GetAllAnnotationsForCampaignResponses];

export type GetTimeseriesForCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries';
};

export type GetTimeseriesForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeseriesForCampaignError = GetTimeseriesForCampaignErrors[keyof GetTimeseriesForCampaignErrors];

export type GetTimeseriesForCampaignResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesListResponse;
};

export type GetTimeseriesForCampaignResponse = GetTimeseriesForCampaignResponses[keyof GetTimeseriesForCampaignResponses];

export type CreateTimeseriesForCampaignData = {
    body: TimeseriesBulkCreateRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries';
};

export type CreateTimeseriesForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTimeseriesForCampaignError = CreateTimeseriesForCampaignErrors[keyof CreateTimeseriesForCampaignErrors];

export type CreateTimeseriesForCampaignResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesBulkCreateResponse;
};

export type CreateTimeseriesForCampaignResponse = CreateTimeseriesForCampaignResponses[keyof CreateTimeseriesForCampaignResponses];

export type GetTimeseriesCreationOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/timeseries/create-options';
};

export type GetTimeseriesCreationOptionsResponses = {
    /**
     * Successful Response
     */
    200: TimeSeriesOptionsOut;
};

export type GetTimeseriesCreationOptionsResponse = GetTimeseriesCreationOptionsResponses[keyof GetTimeseriesCreationOptionsResponses];

export type GetTimeseriesDataData = {
    body?: never;
    path: {
        /**
         * Timeseries Id
         */
        timeseries_id: number;
        /**
         * Latitude
         */
        latitude: number;
        /**
         * Longitude
         */
        longitude: number;
    };
    query?: never;
    url: '/api/timeseries/{timeseries_id}/{latitude}/{longitude}/data';
};

export type GetTimeseriesDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeseriesDataError = GetTimeseriesDataErrors[keyof GetTimeseriesDataErrors];

export type GetTimeseriesDataResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesDataResponse;
};

export type GetTimeseriesDataResponse = GetTimeseriesDataResponses[keyof GetTimeseriesDataResponses];

export type DeleteTimeseriesData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Timeseries Id
         */
        timeseries_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries/{timeseries_id}';
};

export type DeleteTimeseriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTimeseriesError = DeleteTimeseriesErrors[keyof DeleteTimeseriesErrors];

export type DeleteTimeseriesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTimeseriesResponse = DeleteTimeseriesResponses[keyof DeleteTimeseriesResponses];

export type GenerateTasksFromSamplingData = {
    body: BodyGenerateTasksFromSampling;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/sampling/generate-tasks';
};

export type GenerateTasksFromSamplingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTasksFromSamplingError = GenerateTasksFromSamplingErrors[keyof GenerateTasksFromSamplingErrors];

export type GenerateTasksFromSamplingResponses = {
    /**
     * Successful Response
     */
    200: GenerateTasksResponse;
};

export type GenerateTasksFromSamplingResponse = GenerateTasksFromSamplingResponses[keyof GenerateTasksFromSamplingResponses];

export type CreateImageryData = {
    body: ImageryEditorStateCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery';
};

export type CreateImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateImageryError = CreateImageryErrors[keyof CreateImageryErrors];

export type CreateImageryResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type CreateNewCanvasLayoutData = {
    body: CanvasLayoutCreateRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/new-layout';
};

export type CreateNewCanvasLayoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewCanvasLayoutError = CreateNewCanvasLayoutErrors[keyof CreateNewCanvasLayoutErrors];

export type CreateNewCanvasLayoutResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteSourceData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/sources/{source_id}';
};

export type DeleteSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSourceError = DeleteSourceErrors[keyof DeleteSourceErrors];

export type DeleteSourceResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSourceResponse = DeleteSourceResponses[keyof DeleteSourceResponses];

export type UpdateSourceData = {
    body: ImagerySourceUpdate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/sources/{source_id}';
};

export type UpdateSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSourceError = UpdateSourceErrors[keyof UpdateSourceErrors];

export type UpdateSourceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCollectionData = {
    body: ImageryCollectionUpdate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Collection Id
         */
        collection_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/collections/{collection_id}';
};

export type UpdateCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCollectionError = UpdateCollectionErrors[keyof UpdateCollectionErrors];

export type UpdateCollectionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshCollectionImageryData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Collection Id
         */
        collection_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/collections/{collection_id}/refresh';
};

export type RefreshCollectionImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshCollectionImageryError = RefreshCollectionImageryErrors[keyof RefreshCollectionImageryErrors];

export type RefreshCollectionImageryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateVizParamsData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Collection Id
         */
        collection_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/collections/{collection_id}/viz-params';
};

export type UpdateVizParamsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVizParamsError = UpdateVizParamsErrors[keyof UpdateVizParamsErrors];

export type UpdateVizParamsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTileUrlsData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Collection Id
         */
        collection_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/collections/{collection_id}/tile-urls';
};

export type UpdateTileUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTileUrlsError = UpdateTileUrlsErrors[keyof UpdateTileUrlsErrors];

export type UpdateTileUrlsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddViewData = {
    body: ImageryViewAddRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/views';
};

export type AddViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddViewError = AddViewErrors[keyof AddViewErrors];

export type AddViewResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteViewData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * View Id
         */
        view_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/views/{view_id}';
};

export type DeleteViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteViewError = DeleteViewErrors[keyof DeleteViewErrors];

export type DeleteViewResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteViewResponse = DeleteViewResponses[keyof DeleteViewResponses];

export type UpdateViewData = {
    body: ImageryViewUpdate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * View Id
         */
        view_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/views/{view_id}';
};

export type UpdateViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateViewError = UpdateViewErrors[keyof UpdateViewErrors];

export type UpdateViewResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReorderViewsData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/views/reorder';
};

export type ReorderViewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderViewsError = ReorderViewsErrors[keyof ReorderViewsErrors];

export type ReorderViewsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListCatalogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stac/catalogs';
};

export type ListCatalogsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCollectionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Catalog Url
         *
         * STAC API URL
         */
        catalog_url: string;
    };
    url: '/api/stac/collections';
};

export type GetCollectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCollectionsError = GetCollectionsErrors[keyof GetCollectionsErrors];

export type GetCollectionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/stac/search';
};

export type SearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchResponse2 = SearchResponses[keyof SearchResponses];

export type RegisterMosaicData = {
    body: MosaicRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/stac/mosaic/register';
};

export type RegisterMosaicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterMosaicError = RegisterMosaicErrors[keyof RegisterMosaicErrors];

export type RegisterMosaicResponses = {
    /**
     * Successful Response
     */
    200: MosaicRegisterResponse;
};

export type RegisterMosaicResponse = RegisterMosaicResponses[keyof RegisterMosaicResponses];
