"""create annotation tables

Revision ID: 087ef48a2b45
Revises: ecdf64d23d4e
Create Date: 2025-12-22 19:03:45.367887

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "087ef48a2b45"
down_revision: Union[str, Sequence[str], None] = "ecdf64d23d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_geometries",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "annotation_task_items",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("annotation_number", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("geometry_id", sa.Integer(), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("raw_source_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["assigned_user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["geometry_id"], ["data.annotation_geometries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "annotation_number"),
        schema="data",
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("geometry_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("annotation_task_item_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_task_item_id"], ["data.annotation_task_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["auth.users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["geometry_id"], ["data.annotation_geometries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotations", schema="data")
    op.drop_table("annotation_task_items", schema="data")
    op.drop_table("annotation_geometries", schema="data")
    # ### end Alembic commands ###
