"""add default_main_window_id to imagery

Revision ID: 20c690e91954
Revises: 41529171c6ee
Create Date: 2025-12-26 18:47:07.456292

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c690e91954"
down_revision: str | Sequence[str] | None = "41529171c6ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "imagery", sa.Column("default_main_window_id", sa.Integer(), nullable=True), schema="data"
    )
    # ### end Alembic commands ###

    # Data migration: Set default_main_window_id to the middle window for existing imagery
    conn = op.get_bind()

    # Get all imagery IDs
    imagery_ids = conn.execute(text("SELECT id FROM data.imagery")).fetchall()

    for (imagery_id,) in imagery_ids:
        # Get windows for this imagery, ordered by start date
        windows = conn.execute(
            text("""
                SELECT id
                FROM data.imagery_windows
                WHERE imagery_id = :imagery_id
                ORDER BY window_start_date
            """),
            {"imagery_id": imagery_id},
        ).fetchall()

        if windows:
            # Calculate middle index
            middle_index = len(windows) // 2
            middle_window_id = windows[middle_index][0]

            # Update imagery with middle window ID
            conn.execute(
                text("""
                    UPDATE data.imagery
                    SET default_main_window_id = :window_id
                    WHERE id = :imagery_id
                """),
                {"window_id": middle_window_id, "imagery_id": imagery_id},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imagery", "default_main_window_id", schema="data")
    # ### end Alembic commands ###
