"""adding layouts to imagery and campaigns

Revision ID: 41529171c6ee
Revises: f214fa91bfb7
Create Date: 2025-12-26 14:02:00.546390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41529171c6ee"
down_revision: Union[str, Sequence[str], None] = "f214fa91bfb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canvas_layouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "layout_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.drop_table("imagery_slices", schema="data")
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
        schema="auth",
    )
    op.create_unique_constraint(
        "uq_annotation_task_id", "annotations", ["annotation_task_id"], schema="data"
    )
    op.add_column(
        "campaigns",
        sa.Column("default_main_canvas_layout_id", sa.Integer(), nullable=False),
        schema="data",
    )
    op.create_foreign_key(
        None,
        "campaigns",
        "canvas_layouts",
        ["default_main_canvas_layout_id"],
        ["id"],
        source_schema="data",
        referent_schema="data",
        ondelete="CASCADE",
    )
    op.add_column(
        "imagery",
        sa.Column("default_canvas_layout_id", sa.Integer(), nullable=False),
        schema="data",
    )
    op.create_foreign_key(
        None,
        "imagery",
        "canvas_layouts",
        ["default_canvas_layout_id"],
        ["id"],
        source_schema="data",
        referent_schema="data",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "imagery", schema="data", type_="foreignkey")
    op.drop_column("imagery", "default_canvas_layout_id", schema="data")
    op.drop_constraint(None, "campaigns", schema="data", type_="foreignkey")
    op.drop_column("campaigns", "default_main_canvas_layout_id", schema="data")
    op.drop_constraint("uq_annotation_task_id", "annotations", schema="data", type_="unique")
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        schema="auth",
    )
    op.create_table(
        "imagery_slices",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("imagery_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("window_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("slice_start_date", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("slice_end_date", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("index_in_window", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("stac_search_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["imagery_id"],
            ["data.imagery.id"],
            name=op.f("imagery_slices_imagery_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["window_id"],
            ["data.imagery_windows.id"],
            name=op.f("imagery_slices_window_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("imagery_slices_pkey")),
        schema="data",
    )
    op.drop_table("canvas_layouts", schema="data")
    # ### end Alembic commands ###
