"""add imagery windowing stac columns

Revision ID: 454aa9123d3f
Revises: e37d96fcbc0a
Create Date: 2025-12-25 16:12:21.931425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "454aa9123d3f"
down_revision: Union[str, Sequence[str], None] = "e37d96fcbc0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_task_items_campaign_id",
        "annotation_task_items",
        ["campaign_id"],
        unique=False,
        schema="data",
    )
    op.create_index(
        "idx_annotations_campaign_id", "annotations", ["campaign_id"], unique=False, schema="data"
    )
    op.add_column(
        "imagery", sa.Column("window_interval", sa.Integer(), nullable=True), schema="data"
    )
    op.add_column("imagery", sa.Column("window_unit", sa.String(), nullable=True), schema="data")
    op.add_column(
        "imagery", sa.Column("slicing_interval", sa.Integer(), nullable=True), schema="data"
    )
    op.add_column("imagery", sa.Column("slicing_unit", sa.String(), nullable=True), schema="data")
    op.add_column(
        "imagery", sa.Column("registration_url", sa.String(), nullable=False), schema="data"
    )
    op.add_column(
        "imagery",
        sa.Column("search_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imagery", "search_body", schema="data")
    op.drop_column("imagery", "registration_url", schema="data")
    op.drop_column("imagery", "slicing_unit", schema="data")
    op.drop_column("imagery", "slicing_interval", schema="data")
    op.drop_column("imagery", "window_unit", schema="data")
    op.drop_column("imagery", "window_interval", schema="data")
    op.drop_index("idx_annotations_campaign_id", table_name="annotations", schema="data")
    op.drop_index("idx_task_items_campaign_id", table_name="annotation_task_items", schema="data")
    # ### end Alembic commands ###
