"""added campaign mode

Revision ID: 6ab7e9e1fec0
Revises: 80d56b18a9df
Create Date: 2026-01-03 17:10:09.755318

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ab7e9e1fec0"
down_revision: str | Sequence[str] | None = "80d56b18a9df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column(
        "campaigns", sa.Column("mode", sa.String(length=20), nullable=True), schema="data"
    )
    # Update existing rows with default value
    op.execute("UPDATE data.campaigns SET mode = 'tasks' WHERE mode IS NULL")
    # Make column NOT NULL
    op.alter_column("campaigns", "mode", nullable=False, schema="data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "mode", schema="data")
    # ### end Alembic commands ###
