"""added window index

Revision ID: 6ecd27f51949
Revises: 20c690e91954
Create Date: 2025-12-29 13:10:24.334241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ecd27f51949"
down_revision: Union[str, Sequence[str], None] = "20c690e91954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column(
        "imagery_windows", sa.Column("window_index", sa.Integer(), nullable=True), schema="data"
    )

    # Populate window_index for existing entries based on chronological order of windows
    # Use ROW_NUMBER() partitioned by imagery_id and ordered by window_start_date
    op.execute("""
        UPDATE data.imagery_windows
        SET window_index = subquery.row_num - 1
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY imagery_id ORDER BY window_start_date, window_end_date) - 1 AS row_num
            FROM data.imagery_windows
        ) AS subquery
        WHERE data.imagery_windows.id = subquery.id
    """)

    # Make column non-nullable after populating
    op.alter_column("imagery_windows", "window_index", nullable=False, schema="data")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imagery_windows", "window_index", schema="data")
    # ### end Alembic commands ###
