"""add_is_authorative_flag_for_anns

Revision ID: 748e1a963a72
Revises: f5283844a784
Create Date: 2026-02-01 13:25:01.325999

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "748e1a963a72"
down_revision: str | Sequence[str] | None = "f5283844a784"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_task_items_campaign_id",
        "annotation_tasks",
        ["campaign_id"],
        unique=False,
        schema="data",
    )
    op.add_column(
        "annotations",
        sa.Column(
            "is_authoritative", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("annotations", "is_authoritative", schema="data")
    op.drop_index("idx_task_items_campaign_id", table_name="annotation_tasks", schema="data")
    # ### end Alembic commands ###
