"""adding timeseries and refactoring tables

Revision ID: 97f7875c837c
Revises: 6ecd27f51949
Create Date: 2025-12-30 16:17:28.984033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97f7875c837c"
down_revision: Union[str, Sequence[str], None] = "6ecd27f51949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "time_series", sa.Column("data_source", sa.String(), nullable=False), schema="data"
    )
    op.add_column("time_series", sa.Column("provider", sa.String(), nullable=False), schema="data")
    op.add_column("time_series", sa.Column("ts_type", sa.String(), nullable=False), schema="data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("time_series", "ts_type", schema="data")
    op.drop_column("time_series", "provider", schema="data")
    op.drop_column("time_series", "data_source", schema="data")
    # ### end Alembic commands ###
