"""initial auth and campaigns schema

Revision ID: cc5e7947d19c
Revises:
Create Date: 2025-12-16 12:39:14.112919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc5e7947d19c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS data")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("external_uid", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "last_login",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "external_uid", name="users_issuer_external_uid_uniq"),
        schema="auth",
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.CheckConstraint("role IN ('user', 'approved', 'admin')", name="user_roles_role_check"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role"),
        schema="auth",
    )
    op.create_index(
        "user_roles_user_id_idx", "user_roles", ["user_id"], unique=False, schema="auth"
    )
    op.create_table(
        "campaign_users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.CheckConstraint("role IN ('member', 'admin')", name="campaign_users_role_check"),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "campaign_id"),
        schema="data",
    )
    op.create_table(
        "imagery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("start_ym", sa.String(length=6), nullable=False),
        sa.Column("end_ym", sa.String(length=6), nullable=False),
        sa.Column("crosshair_hex6", sa.String(length=6), server_default="ff0000", nullable=False),
        sa.Column("default_zoom", sa.SmallInteger(), server_default="12", nullable=False),
        sa.CheckConstraint("default_zoom BETWEEN 0 AND 22", name="imagery_default_zoom_check"),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "settings",
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column(
            "target_classes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("bbox_west", sa.Float(), nullable=False),
        sa.Column("bbox_south", sa.Float(), nullable=False),
        sa.Column("bbox_east", sa.Float(), nullable=False),
        sa.Column("bbox_north", sa.Float(), nullable=False),
        sa.CheckConstraint("bbox_east BETWEEN -180 AND 180", name="settings_bbox_east_range"),
        sa.CheckConstraint("bbox_north BETWEEN -90 AND 90", name="settings_bbox_north_range"),
        sa.CheckConstraint("bbox_south < bbox_north", name="settings_bbox_lat_order"),
        sa.CheckConstraint("bbox_south BETWEEN -90 AND 90", name="settings_bbox_south_range"),
        sa.CheckConstraint("bbox_west < bbox_east", name="settings_bbox_lon_order"),
        sa.CheckConstraint("bbox_west BETWEEN -180 AND 180", name="settings_bbox_west_range"),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("campaign_id"),
        schema="data",
    )
    op.create_table(
        "time_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("start_ym", sa.String(length=6), nullable=False),
        sa.Column("end_ym", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_series", schema="data")
    op.drop_table("settings", schema="data")
    op.drop_table("imagery", schema="data")
    op.drop_table("campaign_users", schema="data")
    op.drop_index("user_roles_user_id_idx", table_name="user_roles", schema="auth")
    op.drop_table("user_roles", schema="auth")
    op.drop_table("campaigns", schema="data")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
