"""qualtiy-assurance-functionality

Revision ID: cf49671afcb5
Revises: 6ab7e9e1fec0
Create Date: 2026-01-31 10:27:22.282173

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf49671afcb5"
down_revision: str | Sequence[str] | None = "6ab7e9e1fec0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema with data migration."""
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()

    # Step 0: Check if old annotation_tasks table exists and rename it
    if connection.dialect.has_table(connection, "annotation_tasks", schema="data"):
        # Drop the index from the old table before renaming
        try:
            op.drop_index(
                "idx_task_items_campaign_id", table_name="annotation_tasks", schema="data"
            )
        except:
            pass  # Index might not exist
        # Rename old table temporarily
        op.rename_table("annotation_tasks", "annotation_task_items", schema="data")

    # Step 1: Create new annotation_tasks table
    op.create_table(
        "annotation_tasks",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("annotation_number", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("geometry_id", sa.Integer(), nullable=False),
        sa.Column("raw_source_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["data.campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["geometry_id"], ["data.annotation_geometries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "annotation_number"),
        schema="data",
    )
    # Create index only if it doesn't already exist
    index_exists = (
        connection.execute(
            sa.text("""
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'idx_task_items_campaign_id'
          AND n.nspname = 'data'
        LIMIT 1
    """)
        ).fetchone()
        is not None
    )
    if not index_exists:
        op.create_index(
            "idx_task_items_campaign_id",
            "annotation_tasks",
            ["campaign_id"],
            unique=False,
            schema="data",
        )
    op.create_table(
        "annotation_tasks_assignment",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["data.annotation_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "user_id"),
        schema="data",
    )
    op.create_index(
        "idx_annotation_tasks_assignment_task_id",
        "annotation_tasks_assignment",
        ["task_id"],
        unique=False,
        schema="data",
    )

    # Step 2: Migrate data from annotation_task_items to annotation_tasks
    # (if annotation_task_items table exists)
    connection = op.get_bind()
    if connection.dialect.has_table(connection, "annotation_task_items", schema="data"):
        # Copy task data (excluding assignment info) - use OVERRIDING SYSTEM VALUE for identity column
        op.execute("""
            INSERT INTO data.annotation_tasks (id, annotation_number, campaign_id, geometry_id, raw_source_data)
            OVERRIDING SYSTEM VALUE
            SELECT id, annotation_number, campaign_id, geometry_id, raw_source_data
            FROM data.annotation_task_items
        """)

        # Create assignments for tasks that have assigned users
        op.execute("""
            INSERT INTO data.annotation_tasks_assignment (task_id, user_id, status)
            SELECT id, assigned_user_id, status
            FROM data.annotation_task_items
            WHERE assigned_user_id IS NOT NULL
        """)

        # Update sequence for annotation_tasks to match
        op.execute("""
            SELECT setval(
                pg_get_serial_sequence('data.annotation_tasks', 'id'),
                COALESCE((SELECT MAX(id) FROM data.annotation_tasks), 1),
                true
            )
        """)

    # Step 3: Update annotations table BEFORE dropping old table
    # Add new columns (check if they don't already exist)
    if not connection.dialect.has_table(connection, "annotation_task_items", schema="data"):
        # Fresh migration - columns don't exist yet
        op.add_column(
            "annotations",
            sa.Column("annotation_task_id", sa.Integer(), nullable=True),
            schema="data",
        )
        op.add_column(
            "annotations", sa.Column("confidence", sa.Integer(), nullable=True), schema="data"
        )

        # Create foreign key and index
        op.create_index(
            "idx_annotations_task_id",
            "annotations",
            ["annotation_task_id"],
            unique=False,
            schema="data",
        )
        op.create_foreign_key(
            None,
            "annotations",
            "annotation_tasks",
            ["annotation_task_id"],
            ["id"],
            source_schema="data",
            referent_schema="data",
            ondelete="SET NULL",
        )
    else:
        # Migration from old table - need to handle existing columns
        # Add confidence column (new in this migration)
        try:
            op.add_column(
                "annotations", sa.Column("confidence", sa.Integer(), nullable=True), schema="data"
            )
        except:
            pass  # Column might already exist

        # Check if old column exists by querying information_schema
        result = connection.execute(
            sa.text("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'data'
            AND table_name = 'annotations'
            AND column_name = 'annotation_task_item_id'
        """)
        )
        has_old_column = result.fetchone() is not None

        if has_old_column:
            # Add new column
            try:
                op.add_column(
                    "annotations",
                    sa.Column("annotation_task_id", sa.Integer(), nullable=True),
                    schema="data",
                )
            except:
                pass  # Column might already exist

            # Migrate data
            op.execute("""
                UPDATE data.annotations
                SET annotation_task_id = annotation_task_item_id
                WHERE annotation_task_item_id IS NOT NULL
            """)

            # Drop old constraints and column
            try:
                op.drop_constraint(
                    op.f("uq_annotation_task_item_id"), "annotations", schema="data", type_="unique"
                )
            except Exception as e:
                pass
            try:
                op.drop_constraint(
                    op.f("annotations_annotation_task_item_id_fkey"),
                    "annotations",
                    schema="data",
                    type_="foreignkey",
                )
            except:
                pass

            # Create new index and foreign key
            op.create_index(
                "idx_annotations_task_id",
                "annotations",
                ["annotation_task_id"],
                unique=False,
                schema="data",
            )
            op.create_foreign_key(
                None,
                "annotations",
                "annotation_tasks",
                ["annotation_task_id"],
                ["id"],
                source_schema="data",
                referent_schema="data",
                ondelete="SET NULL",
            )

            # Drop old column
            op.drop_column("annotations", "annotation_task_item_id", schema="data")

    # Step 4: NOW drop old annotation_task_items table (if exists)
    if connection.dialect.has_table(connection, "annotation_task_items", schema="data"):
        # Drop foreign key from annotations table first
        try:
            # Query for the actual foreign key constraint name
            result = connection.execute(
                sa.text("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_schema = 'data'
                AND table_name = 'annotations'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%annotation_task%'
            """)
            )
            for row in result:
                try:
                    op.drop_constraint(row[0], "annotations", schema="data", type_="foreignkey")
                except Exception:
                    pass
        except Exception:
            pass

        # Drop index and table
        try:
            op.drop_index(
                op.f("idx_task_items_campaign_id"),
                table_name="annotation_task_items",
                schema="data",
            )
        except Exception:
            pass
        op.execute("DROP TABLE IF EXISTS data.annotation_task_items CASCADE")

    # Step 5: Update campaign_users table - migrate role to boolean flags
    # Add new columns with temporary nullable state
    op.add_column(
        "campaign_users", sa.Column("is_admin", sa.Boolean(), nullable=True), schema="data"
    )
    op.add_column(
        "campaign_users",
        sa.Column("is_authorative_reviewer", sa.Boolean(), nullable=True),
        schema="data",
    )

    # Migrate existing role data to new boolean columns
    # Assuming previous roles were: 'admin', 'reviewer', 'annotator' or similar
    op.execute("""
        UPDATE data.campaign_users
        SET
            is_admin = CASE WHEN role = 'admin' THEN true ELSE false END,
            is_authorative_reviewer = CASE WHEN role IN ('admin', 'reviewer') THEN true ELSE false END
    """)

    # Make columns non-nullable and set defaults for any NULL values
    op.execute("UPDATE data.campaign_users SET is_admin = false WHERE is_admin IS NULL")
    op.execute(
        "UPDATE data.campaign_users SET is_authorative_reviewer = false WHERE is_authorative_reviewer IS NULL"
    )
    op.alter_column("campaign_users", "is_admin", nullable=False, schema="data")
    op.alter_column("campaign_users", "is_authorative_reviewer", nullable=False, schema="data")

    # Drop old role column
    op.drop_column("campaign_users", "role", schema="data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - WARNING: This will lose data!"""
    # ### commands auto generated by Alembic - please adjust! ###

    # Restore campaign_users.role column
    op.add_column(
        "campaign_users",
        sa.Column("role", sa.TEXT(), autoincrement=False, nullable=True),
        schema="data",
    )

    # Attempt to restore role from boolean flags (will default to 'annotator' for most)
    op.execute("""
        UPDATE data.campaign_users
        SET role = CASE
            WHEN is_admin THEN 'admin'
            WHEN is_authorative_reviewer THEN 'reviewer'
            ELSE 'annotator'
        END
    """)

    op.alter_column("campaign_users", "role", nullable=False, schema="data")
    op.drop_column("campaign_users", "is_authorative_reviewer", schema="data")
    op.drop_column("campaign_users", "is_admin", schema="data")

    # Restore annotation_task_item_id column
    op.add_column(
        "annotations",
        sa.Column("annotation_task_item_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="data",
    )
    op.execute(
        "UPDATE data.annotations SET annotation_task_item_id = annotation_task_id WHERE annotation_task_id IS NOT NULL"
    )
    op.drop_constraint(None, "annotations", schema="data", type_="foreignkey")

    # Recreate annotation_task_items table
    op.create_table(
        "annotation_task_items",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("annotation_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("campaign_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("geometry_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'pending'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "raw_source_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["auth.users.id"],
            name=op.f("annotation_task_items_assigned_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["data.campaigns.id"],
            name=op.f("annotation_task_items_campaign_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["geometry_id"],
            ["data.annotation_geometries.id"],
            name=op.f("annotation_task_items_geometry_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("annotation_task_items_pkey")),
        sa.UniqueConstraint(
            "campaign_id",
            "annotation_number",
            name=op.f("annotation_task_items_campaign_id_annotation_number_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema="data",
    )
    op.create_index(
        op.f("idx_task_items_campaign_id"),
        "annotation_task_items",
        ["campaign_id"],
        unique=False,
        schema="data",
    )

    # Migrate data back from annotation_tasks (keep only first assignment)
    op.execute("""
        INSERT INTO data.annotation_task_items (id, annotation_number, campaign_id, geometry_id, assigned_user_id, status, raw_source_data)
        OVERRIDING SYSTEM VALUE
        SELECT
            t.id,
            t.annotation_number,
            t.campaign_id,
            t.geometry_id,
            a.user_id,
            a.status,
            t.raw_source_data
        FROM data.annotation_tasks t
        LEFT JOIN LATERAL (
            SELECT user_id, status
            FROM data.annotation_tasks_assignment
            WHERE task_id = t.id
            LIMIT 1
        ) a ON true
    """)

    op.create_foreign_key(
        op.f("annotations_annotation_task_item_id_fkey"),
        "annotations",
        "annotation_task_items",
        ["annotation_task_item_id"],
        ["id"],
        source_schema="data",
        referent_schema="data",
        ondelete="SET NULL",
    )
    op.drop_index("idx_annotations_task_id", table_name="annotations", schema="data")
    op.create_unique_constraint(
        op.f("uq_annotation_task_item_id"),
        "annotations",
        ["annotation_task_item_id"],
        schema="data",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("annotations", "confidence", schema="data")
    op.drop_column("annotations", "annotation_task_id", schema="data")

    # Drop new tables
    op.drop_index(
        "idx_annotation_tasks_assignment_task_id",
        table_name="annotation_tasks_assignment",
        schema="data",
    )
    op.drop_table("annotation_tasks_assignment", schema="data")
    op.drop_index("idx_task_items_campaign_id", table_name="annotation_tasks", schema="data")
    op.drop_table("annotation_tasks", schema="data")
    # ### end Alembic commands ###

    op.drop_index(
        "idx_annotation_tasks_assignment_task_id",
        table_name="annotation_tasks_assignment",
        schema="data",
    )
    op.drop_table("annotation_tasks_assignment", schema="data")
    op.drop_index("idx_task_items_campaign_id", table_name="annotation_tasks", schema="data")
    op.drop_table("annotation_tasks", schema="data")
    # ### end Alembic commands ###
