"""adding imagery configs

Revision ID: e37d96fcbc0a
Revises: f5bd1b96c424
Create Date: 2025-12-25 14:03:34.340933

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e37d96fcbc0a"
down_revision: str | Sequence[str] | None = "f5bd1b96c424"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imagery_tile_url_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imagery_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tile_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["imagery_id"], ["data.imagery.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "imagery_windows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imagery_id", sa.Integer(), nullable=False),
        sa.Column("window_start_date", sa.String(length=8), nullable=False),
        sa.Column("window_end_date", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["imagery_id"], ["data.imagery.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    op.create_table(
        "imagery_slices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imagery_id", sa.Integer(), nullable=False),
        sa.Column("imagery_tile_url_template_id", sa.Integer(), nullable=False),
        sa.Column("window_id", sa.Integer(), nullable=False),
        sa.Column("slice_start_date", sa.String(length=8), nullable=False),
        sa.Column("slice_end_date", sa.String(length=8), nullable=False),
        sa.Column("index_in_window", sa.Integer(), nullable=False),
        sa.Column("stac_search_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["imagery_id"], ["data.imagery.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["imagery_tile_url_template_id"],
            ["data.imagery_tile_url_templates.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["window_id"], ["data.imagery_windows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("imagery_slices", schema="data")
    op.drop_table("imagery_windows", schema="data")
    op.drop_table("imagery_tile_url_templates", schema="data")
    # ### end Alembic commands ###
