"""rename tile_url_template to visualization_url_template

Revision ID: f214fa91bfb7
Revises: 454aa9123d3f
Create Date: 2025-12-25 17:55:31.863840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f214fa91bfb7"
down_revision: Union[str, Sequence[str], None] = "454aa9123d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint
    op.drop_constraint(
        op.f("imagery_slices_imagery_tile_url_template_id_fkey"),
        "imagery_slices",
        schema="data",
        type_="foreignkey",
    )
    op.drop_column("imagery_slices", "imagery_tile_url_template_id", schema="data")

    # Then drop the old table
    op.drop_table("imagery_tile_url_templates", schema="data")

    # Finally, create the new table
    op.create_table(
        "imagery_visualization_url_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("imagery_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("visualization_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["imagery_id"], ["data.imagery.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the new table
    op.drop_table("imagery_visualization_url_templates", schema="data")

    # Recreate the old table
    op.create_table(
        "imagery_tile_url_templates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("imagery_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("tile_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["imagery_id"],
            ["data.imagery.id"],
            name=op.f("imagery_tile_url_templates_imagery_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("imagery_tile_url_templates_pkey")),
        schema="data",
    )

    # Finally, recreate the column and foreign key constraint
    op.add_column(
        "imagery_slices",
        sa.Column(
            "imagery_tile_url_template_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        schema="data",
    )
    op.create_foreign_key(
        op.f("imagery_slices_imagery_tile_url_template_id_fkey"),
        "imagery_slices",
        "imagery_tile_url_templates",
        ["imagery_tile_url_template_id"],
        ["id"],
        source_schema="data",
        referent_schema="data",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
