"""fix-annotation-task-constraint

Revision ID: f5283844a784
Revises: cf49671afcb5
Create Date: 2026-01-31 12:24:04.085735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5283844a784'
down_revision: Union[str, Sequence[str], None] = 'cf49671afcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Remove unique constraint on annotation_task_id to allow multiple annotations per task."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unique constraint and add index instead - allows multiple users to annotate same task
    op.drop_constraint(op.f('uq_annotation_task_id'), 'annotations', schema='data', type_='unique')
    op.create_index('idx_annotations_task_id', 'annotations', ['annotation_task_id'], unique=False, schema='data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore unique constraint (WARNING: will fail if multiple annotations exist for same task)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_annotations_task_id', table_name='annotations', schema='data')
    op.create_unique_constraint(op.f('uq_annotation_task_id'), 'annotations', ['annotation_task_id'], schema='data', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
