// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnnotationCreate
 */
export type AnnotationCreate = {
    /**
     * Label Id
     */
    label_id: number;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Geometry Wkt
     */
    geometry_wkt: string;
};

/**
 * AnnotationFromTaskCreate
 */
export type AnnotationFromTaskCreate = {
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
};

/**
 * AnnotationFromTaskOut
 */
export type AnnotationFromTaskOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created By User Id
     */
    created_by_user_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AnnotationOut
 */
export type AnnotationOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Created By User Id
     */
    created_by_user_id: string;
    /**
     * Created At
     */
    created_at: string;
    geometry: GeometryOut;
};

/**
 * AnnotationTaskItemOut
 */
export type AnnotationTaskItemOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Annotation Number
     */
    annotation_number: number;
    geometry: GeometryOut;
    /**
     * Status
     */
    status: string;
    assigned_user: UserOut | null;
    annotation: AnnotationFromTaskOut | null;
};

/**
 * AnnotationTaskListOut
 */
export type AnnotationTaskListOut = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Tasks
     */
    tasks: Array<AnnotationTaskItemOut>;
};

/**
 * AnnotationUpdate
 */
export type AnnotationUpdate = {
    /**
     * Label Id
     */
    label_id: number | null;
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Geometry Wkt
     */
    geometry_wkt: string | null;
};

/**
 * AssignTasksToUsersRequest
 *
 * Request to assign multiple tasks to users.
 * Maps task IDs to user IDs.
 */
export type AssignTasksToUsersRequest = {
    /**
     * Task Assignments
     */
    task_assignments: {
        [key: string]: string;
    };
};

/**
 * AssignUsersToCampaignRequest
 */
export type AssignUsersToCampaignRequest = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * Body_generateTasksFromSampling
 */
export type BodyGenerateTasksFromSampling = {
    /**
     * Strategy
     *
     * JSON string of SamplingStrategyConfig
     */
    strategy: string;
    /**
     * Region File
     *
     * Region boundary file (.zip shapefile or .geojson). Optional if using campaign bbox.
     */
    region_file?: Blob | File | null;
};

/**
 * Body_ingestAnnotationTaskFromCsv
 */
export type BodyIngestAnnotationTaskFromCsv = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BulkUserActionRequest
 *
 * Request body for bulk user operations.
 */
export type BulkUserActionRequest = {
    /**
     * User Ids
     */
    user_ids: Array<string>;
};

/**
 * BulkUserActionResponse
 *
 * Response for bulk user operations.
 */
export type BulkUserActionResponse = {
    /**
     * Success
     */
    success: Array<UserOutDetailed>;
    /**
     * Not Found
     */
    not_found: Array<string>;
    /**
     * Already In State
     */
    already_in_state: Array<UserOutDetailed>;
};

/**
 * CampaignCreate
 */
export type CampaignCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Mode
     */
    mode: string;
    settings: CampaignSettingsCreate;
    /**
     * Imagery Configs
     */
    imagery_configs: Array<ImageryCreate> | null;
    /**
     * Timeseries Configs
     */
    timeseries_configs: Array<TimeSeriesCreate> | null;
};

/**
 * CampaignListItemOut
 */
export type CampaignListItemOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Is Admin
     */
    is_admin?: boolean;
    /**
     * Is Member
     */
    is_member?: boolean;
};

/**
 * CampaignOut
 */
export type CampaignOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    settings: CampaignSettingsOut;
    /**
     * Imagery
     */
    imagery: Array<ImageryOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
};

/**
 * CampaignOutWithImageryWindows
 */
export type CampaignOutWithImageryWindows = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    settings: CampaignSettingsOut;
    /**
     * Imagery
     */
    imagery: Array<ImageryWithWindowsOut>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
    /**
     * Get the default main canvas layout for this campaign.
     */
    readonly default_main_canvas_layout: CanvasLayoutOut | null;
    /**
     * Get the personal main canvas layout for the current user.
     */
    readonly personal_main_canvas_layout: CanvasLayoutOut | null;
};

/**
 * CampaignSettingsCreate
 */
export type CampaignSettingsCreate = {
    /**
     * Labels
     */
    labels: Array<LabelBase>;
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
};

/**
 * CampaignSettingsOut
 */
export type CampaignSettingsOut = {
    /**
     * Labels
     */
    labels: Array<LabelBase>;
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
};

/**
 * CampaignUserOut
 */
export type CampaignUserOut = {
    user: UserOut;
    /**
     * Role
     */
    role: string;
};

/**
 * CampaignUsersResponse
 */
export type CampaignUsersResponse = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Users
     */
    users: Array<CampaignUserOut>;
};

/**
 * CampaignsListResponse
 */
export type CampaignsListResponse = {
    /**
     * Items
     */
    items: Array<CampaignListItemOut>;
};

/**
 * CanvasLayoutCreate
 *
 * Request body to create or update a canvas layout.
 */
export type CanvasLayoutCreate = {
    /**
     * Main Layout Data
     */
    main_layout_data: Array<unknown>;
    /**
     * Imagery Layout Data
     */
    imagery_layout_data?: Array<unknown> | null;
    /**
     * Imagery Id
     */
    imagery_id?: number | null;
};

/**
 * CanvasLayoutCreateRequest
 */
export type CanvasLayoutCreateRequest = {
    layout: CanvasLayoutCreate;
    /**
     * Should Be Default
     */
    should_be_default?: boolean;
    /**
     * Imagery Id
     */
    imagery_id: number;
};

/**
 * CanvasLayoutOut
 *
 * Frontend Canvas layout configuration.
 *
 * Can be either personal or might be the default for the campaign.
 * Typically one layout is either the general section or imagery specific.
 */
export type CanvasLayoutOut = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Layout Data
     */
    layout_data: Array<unknown>;
};

/**
 * CreateImageryResponse
 */
export type CreateImageryResponse = {
    /**
     * New Items
     */
    new_items: Array<ImageryOut>;
};

/**
 * DeleteAnnotationTasksRequest
 *
 * Request to delete multiple annotation tasks.
 */
export type DeleteAnnotationTasksRequest = {
    /**
     * Task Ids
     */
    task_ids: Array<number>;
};

/**
 * GenerateTasksResponse
 *
 * Response after generating tasks.
 */
export type GenerateTasksResponse = {
    /**
     * Campaign Id
     */
    campaign_id: number;
    /**
     * Num Tasks Created
     */
    num_tasks_created: number;
    /**
     * Message
     */
    message: string;
};

/**
 * GeometryOut
 */
export type GeometryOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Geometry
     */
    geometry: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageryBulkCreate
 */
export type ImageryBulkCreate = {
    /**
     * Items
     */
    items: Array<ImageryCreate>;
};

/**
 * ImageryCreate
 */
export type ImageryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6: string;
    /**
     * Default Zoom
     */
    default_zoom: number;
    /**
     * Window Interval
     */
    window_interval?: number | null;
    /**
     * Window Unit
     */
    window_unit?: string | null;
    /**
     * Slicing Interval
     */
    slicing_interval?: number | null;
    /**
     * Slicing Unit
     */
    slicing_unit?: string | null;
    /**
     * Registration Url
     */
    registration_url: string;
    /**
     * Search Body
     */
    search_body: string;
    /**
     * Visualization Url Templates
     */
    visualization_url_templates: Array<ImageryVisualizationUrlTemplateCreate>;
};

/**
 * ImageryOut
 *
 * Represents an imagery dataset configuration within a campaign.
 *
 * Windows define time-windows for seperate visualization chunks of the
 * start and end year-month range. The windows are defined by the window_interval
 * and window_unit fields. For example, a window_interval of 3 and window_unit of
 * 'months' would create 3-month windows within the overall date range.
 *
 * Slicing defines how the imagery data is further sliced within each window. Tjis
 * is often useful to e.g see all imagery within a month. The slicing_interval and slicing_unit
 * fields define this behavior. For example, a slicing_interval of 1 and slicing_unit of
 * 'week' would slice the data into weekly chunks within each window.
 */
export type ImageryOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6: string;
    /**
     * Default Zoom
     */
    default_zoom: number;
    /**
     * Window Interval
     */
    window_interval: number | null;
    /**
     * Window Unit
     */
    window_unit: string | null;
    /**
     * Slicing Interval
     */
    slicing_interval: number | null;
    /**
     * Slicing Unit
     */
    slicing_unit: string | null;
    /**
     * Registration Url
     */
    registration_url: string;
    /**
     * Search Body
     */
    search_body: {
        [key: string]: unknown;
    };
    /**
     * Visualization Url Templates
     */
    visualization_url_templates: Array<ImageryVisualizationUrlTemplateOut>;
};

/**
 * ImageryUpdate
 *
 * Update schema for imagery - excludes temporal fields that cannot be changed
 * after creation (start_ym, end_ym, window_interval, window_unit, slicing_interval, slicing_unit).
 */
export type ImageryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6?: string | null;
    /**
     * Default Zoom
     */
    default_zoom?: number | null;
    /**
     * Registration Url
     */
    registration_url?: string | null;
    /**
     * Search Body
     */
    search_body?: string | null;
    /**
     * Visualization Url Templates
     */
    visualization_url_templates?: Array<ImageryVisualizationUrlTemplateCreate> | null;
};

/**
 * ImageryVisualizationUrlTemplateCreate
 *
 * Defines a (TiTiler) visualization URL template for imagery.
 * The URL must contain {z}, {x}, {y} placeholders for tile access and {searchId} for the search ID.
 */
export type ImageryVisualizationUrlTemplateCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Visualization Url
     */
    visualization_url: string;
};

/**
 * ImageryVisualizationUrlTemplateOut
 *
 * TiTiler visualization URL template for imagery.
 */
export type ImageryVisualizationUrlTemplateOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Visualization Url
     */
    visualization_url: string;
};

/**
 * ImageryWindowOut
 */
export type ImageryWindowOut = {
    /**
     * Window Start Date
     */
    window_start_date: string;
    /**
     * Window End Date
     */
    window_end_date: string;
    /**
     * Id
     */
    id: number;
    /**
     * Window Index
     */
    window_index: number;
};

/**
 * ImageryWithWindowsOut
 *
 * Imagery with associated time-windows.
 */
export type ImageryWithWindowsOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6: string;
    /**
     * Default Zoom
     */
    default_zoom: number;
    /**
     * Window Interval
     */
    window_interval: number | null;
    /**
     * Window Unit
     */
    window_unit: string | null;
    /**
     * Slicing Interval
     */
    slicing_interval: number | null;
    /**
     * Slicing Unit
     */
    slicing_unit: string | null;
    /**
     * Registration Url
     */
    registration_url: string;
    /**
     * Search Body
     */
    search_body: {
        [key: string]: unknown;
    };
    /**
     * Visualization Url Templates
     */
    visualization_url_templates: Array<ImageryVisualizationUrlTemplateOut>;
    /**
     * Default Main Window Id
     */
    default_main_window_id: number;
    /**
     * Windows
     */
    windows: Array<ImageryWindowOut>;
    /**
     * Get the default canvas layout for this imagery.
     */
    readonly default_canvas_layout: CanvasLayoutOut | null;
    /**
     * Get the personal canvas layout for the current user.
     */
    readonly personal_canvas_layout: CanvasLayoutOut | null;
};

/**
 * LabelBase
 *
 * A label that can be assigned to an annotation within a campaign.
 */
export type LabelBase = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * TimeSeriesCreate
 */
export type TimeSeriesCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Ts Type
     */
    ts_type: string;
};

/**
 * TimeSeriesOptionsOut
 */
export type TimeSeriesOptionsOut = {
    /**
     * Data Sources
     */
    data_sources: Array<string>;
    /**
     * Providers
     */
    providers: Array<string>;
    /**
     * Ts Types
     */
    ts_types: Array<string>;
};

/**
 * TimeSeriesOut
 */
export type TimeSeriesOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Ts Type
     */
    ts_type: string;
    /**
     * Id
     */
    id: number;
    /**
     * Campaign Id
     */
    campaign_id: number;
};

/**
 * TimeseriesBulkCreateRequest
 */
export type TimeseriesBulkCreateRequest = {
    /**
     * Timeseries
     */
    timeseries: Array<TimeSeriesCreate>;
};

/**
 * TimeseriesBulkCreateResponse
 */
export type TimeseriesBulkCreateResponse = {
    /**
     * New Items
     */
    new_items: Array<TimeSeriesOut>;
};

/**
 * TimeseriesDataResponse
 */
export type TimeseriesDataResponse = {
    /**
     * Timeseries Id
     */
    timeseries_id: number;
    /**
     * Data
     */
    data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TimeseriesListResponse
 */
export type TimeseriesListResponse = {
    /**
     * Items
     */
    items: Array<TimeSeriesOut>;
};

/**
 * UpdateCampaignBBoxRequest
 */
export type UpdateCampaignBBoxRequest = {
    /**
     * Bbox West
     */
    bbox_west: number;
    /**
     * Bbox South
     */
    bbox_south: number;
    /**
     * Bbox East
     */
    bbox_east: number;
    /**
     * Bbox North
     */
    bbox_north: number;
};

/**
 * UpdateCampaignNameRequest
 */
export type UpdateCampaignNameRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * UserOut
 *
 * Basic user information.
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * UserOutDetailed
 *
 * Detailed user information.
 */
export type UserOutDetailed = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Approved
     */
    is_approved: boolean;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Issuer
     */
    issuer: string;
    /**
     * External Uid
     */
    external_uid: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * CampaignOutWithImageryWindows
 */
export type CampaignOutWithImageryWindowsWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Mode
     */
    mode: string;
    settings: CampaignSettingsOut;
    /**
     * Imagery
     */
    imagery: Array<ImageryWithWindowsOutWritable>;
    /**
     * Time Series
     */
    time_series: Array<TimeSeriesOut>;
};

/**
 * ImageryWithWindowsOut
 *
 * Imagery with associated time-windows.
 */
export type ImageryWithWindowsOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Start Ym
     */
    start_ym: string;
    /**
     * End Ym
     */
    end_ym: string;
    /**
     * Crosshair Hex6
     */
    crosshair_hex6: string;
    /**
     * Default Zoom
     */
    default_zoom: number;
    /**
     * Window Interval
     */
    window_interval: number | null;
    /**
     * Window Unit
     */
    window_unit: string | null;
    /**
     * Slicing Interval
     */
    slicing_interval: number | null;
    /**
     * Slicing Unit
     */
    slicing_unit: string | null;
    /**
     * Registration Url
     */
    registration_url: string;
    /**
     * Search Body
     */
    search_body: {
        [key: string]: unknown;
    };
    /**
     * Visualization Url Templates
     */
    visualization_url_templates: Array<ImageryVisualizationUrlTemplateOut>;
    /**
     * Default Main Window Id
     */
    default_main_window_id: number;
    /**
     * Windows
     */
    windows: Array<ImageryWindowOut>;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/users';
};

export type ListUsersResponses = {
    /**
     * Response Listusers
     *
     * Successful Response
     */
    200: Array<UserOutDetailed>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type EditUserInfoData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query: {
        /**
         * New Display Name
         */
        new_display_name: string;
    };
    url: '/api/auth/users/{user_id}';
};

export type EditUserInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditUserInfoError = EditUserInfoErrors[keyof EditUserInfoErrors];

export type EditUserInfoResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type EditUserInfoResponse = EditUserInfoResponses[keyof EditUserInfoResponses];

export type ApproveUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/approve';
};

export type ApproveUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveUserError = ApproveUserErrors[keyof ApproveUserErrors];

export type ApproveUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type ApproveUserResponse = ApproveUserResponses[keyof ApproveUserResponses];

export type RevokeUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/revoke';
};

export type RevokeUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeUserError = RevokeUserErrors[keyof RevokeUserErrors];

export type RevokeUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type RevokeUserResponse = RevokeUserResponses[keyof RevokeUserResponses];

export type DenyUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/deny';
};

export type DenyUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DenyUserError = DenyUserErrors[keyof DenyUserErrors];

export type DenyUserResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type DenyUserResponse = DenyUserResponses[keyof DenyUserResponses];

export type ApproveUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/approve';
};

export type ApproveUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveUsersBulkError = ApproveUsersBulkErrors[keyof ApproveUsersBulkErrors];

export type ApproveUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type ApproveUsersBulkResponse = ApproveUsersBulkResponses[keyof ApproveUsersBulkResponses];

export type RevokeUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/revoke';
};

export type RevokeUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeUsersBulkError = RevokeUsersBulkErrors[keyof RevokeUsersBulkErrors];

export type RevokeUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type RevokeUsersBulkResponse = RevokeUsersBulkResponses[keyof RevokeUsersBulkResponses];

export type DenyUsersBulkData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/deny';
};

export type DenyUsersBulkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DenyUsersBulkError = DenyUsersBulkErrors[keyof DenyUsersBulkErrors];

export type DenyUsersBulkResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type DenyUsersBulkResponse = DenyUsersBulkResponses[keyof DenyUsersBulkResponses];

export type GrantAdminSingleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/grant-admin';
};

export type GrantAdminSingleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantAdminSingleError = GrantAdminSingleErrors[keyof GrantAdminSingleErrors];

export type GrantAdminSingleResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type GrantAdminSingleResponse = GrantAdminSingleResponses[keyof GrantAdminSingleResponses];

export type RevokeAdminSingleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/auth/users/{user_id}/revoke-admin';
};

export type RevokeAdminSingleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAdminSingleError = RevokeAdminSingleErrors[keyof RevokeAdminSingleErrors];

export type RevokeAdminSingleResponses = {
    /**
     * Successful Response
     */
    200: UserOutDetailed;
};

export type RevokeAdminSingleResponse = RevokeAdminSingleResponses[keyof RevokeAdminSingleResponses];

export type GrantAdminData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/grant-admin';
};

export type GrantAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantAdminError = GrantAdminErrors[keyof GrantAdminErrors];

export type GrantAdminResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type GrantAdminResponse = GrantAdminResponses[keyof GrantAdminResponses];

export type RevokeAdminData = {
    body: BulkUserActionRequest;
    path?: never;
    query?: never;
    url: '/api/auth/users/revoke-admin';
};

export type RevokeAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeAdminError = RevokeAdminErrors[keyof RevokeAdminErrors];

export type RevokeAdminResponses = {
    /**
     * Successful Response
     */
    200: BulkUserActionResponse;
};

export type RevokeAdminResponse = RevokeAdminResponses[keyof RevokeAdminResponses];

export type ListAllCampaignsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/campaigns/';
};

export type ListAllCampaignsResponses = {
    /**
     * Successful Response
     */
    200: CampaignsListResponse;
};

export type ListAllCampaignsResponse = ListAllCampaignsResponses[keyof ListAllCampaignsResponses];

export type CreateCampaignData = {
    body: CampaignCreate;
    path?: never;
    query?: never;
    url: '/api/campaigns/';
};

export type CreateCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCampaignError = CreateCampaignErrors[keyof CreateCampaignErrors];

export type CreateCampaignResponses = {
    /**
     * Successful Response
     */
    201: CampaignOut;
};

export type CreateCampaignResponse = CreateCampaignResponses[keyof CreateCampaignResponses];

export type DeleteCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}';
};

export type DeleteCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCampaignError = DeleteCampaignErrors[keyof DeleteCampaignErrors];

export type DeleteCampaignResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCampaignResponse = DeleteCampaignResponses[keyof DeleteCampaignResponses];

export type GetCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}';
};

export type GetCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignError = GetCampaignErrors[keyof GetCampaignErrors];

export type GetCampaignResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type GetCampaignResponse = GetCampaignResponses[keyof GetCampaignResponses];

export type AddUsersToCampaignData = {
    body: AssignUsersToCampaignRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/assign-users';
};

export type AddUsersToCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUsersToCampaignError = AddUsersToCampaignErrors[keyof AddUsersToCampaignErrors];

export type AddUsersToCampaignResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetCampaignWithImageryWindowsData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/detailed';
};

export type GetCampaignWithImageryWindowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignWithImageryWindowsError = GetCampaignWithImageryWindowsErrors[keyof GetCampaignWithImageryWindowsErrors];

export type GetCampaignWithImageryWindowsResponses = {
    /**
     * Successful Response
     */
    200: CampaignOutWithImageryWindows;
};

export type GetCampaignWithImageryWindowsResponse = GetCampaignWithImageryWindowsResponses[keyof GetCampaignWithImageryWindowsResponses];

export type MakeUserCampaignAdminData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * New Admin User Id
         */
        new_admin_user_id: string;
    };
    url: '/api/campaigns/{campaign_id}/assign-admin';
};

export type MakeUserCampaignAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeUserCampaignAdminError = MakeUserCampaignAdminErrors[keyof MakeUserCampaignAdminErrors];

export type MakeUserCampaignAdminResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetCampaignUsersData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/users';
};

export type GetCampaignUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCampaignUsersError = GetCampaignUsersErrors[keyof GetCampaignUsersErrors];

export type GetCampaignUsersResponses = {
    /**
     * Successful Response
     */
    200: CampaignUsersResponse;
};

export type GetCampaignUsersResponse = GetCampaignUsersResponses[keyof GetCampaignUsersResponses];

export type UpdateCampaignNameData = {
    body: UpdateCampaignNameRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/name';
};

export type UpdateCampaignNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignNameError = UpdateCampaignNameErrors[keyof UpdateCampaignNameErrors];

export type UpdateCampaignNameResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignNameResponse = UpdateCampaignNameResponses[keyof UpdateCampaignNameResponses];

export type UpdateCampaignBboxData = {
    body: UpdateCampaignBBoxRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/bbox';
};

export type UpdateCampaignBboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCampaignBboxError = UpdateCampaignBboxErrors[keyof UpdateCampaignBboxErrors];

export type UpdateCampaignBboxResponses = {
    /**
     * Successful Response
     */
    200: CampaignOut;
};

export type UpdateCampaignBboxResponse = UpdateCampaignBboxResponses[keyof UpdateCampaignBboxResponses];

export type RemoveUserFromCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/users/{user_id}';
};

export type RemoveUserFromCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromCampaignError = RemoveUserFromCampaignErrors[keyof RemoveUserFromCampaignErrors];

export type RemoveUserFromCampaignResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveUserFromCampaignResponse = RemoveUserFromCampaignResponses[keyof RemoveUserFromCampaignResponses];

export type DemoteCampaignAdminData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query: {
        /**
         * User Id
         */
        user_id: string;
    };
    url: '/api/campaigns/{campaign_id}/demote-admin';
};

export type DemoteCampaignAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoteCampaignAdminError = DemoteCampaignAdminErrors[keyof DemoteCampaignAdminErrors];

export type DemoteCampaignAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignTasksToUsersData = {
    body: AssignTasksToUsersRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/assign-tasks';
};

export type AssignTasksToUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignTasksToUsersError = AssignTasksToUsersErrors[keyof AssignTasksToUsersErrors];

export type AssignTasksToUsersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAnnotationTasksData = {
    body: DeleteAnnotationTasksRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotation-tasks';
};

export type DeleteAnnotationTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnnotationTasksError = DeleteAnnotationTasksErrors[keyof DeleteAnnotationTasksErrors];

export type DeleteAnnotationTasksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllAnnotationTasksData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotation-tasks';
};

export type GetAllAnnotationTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAnnotationTasksError = GetAllAnnotationTasksErrors[keyof GetAllAnnotationTasksErrors];

export type GetAllAnnotationTasksResponses = {
    /**
     * Successful Response
     */
    200: AnnotationTaskListOut;
};

export type GetAllAnnotationTasksResponse = GetAllAnnotationTasksResponses[keyof GetAllAnnotationTasksResponses];

export type CompleteAnnotationTaskData = {
    body: AnnotationFromTaskCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Annotation Task Id
         */
        annotation_task_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/{annotation_task_id}/annotate';
};

export type CompleteAnnotationTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteAnnotationTaskError = CompleteAnnotationTaskErrors[keyof CompleteAnnotationTaskErrors];

export type CompleteAnnotationTaskResponses = {
    /**
     * Response Completeannotationtask
     *
     * Successful Response
     */
    200: AnnotationFromTaskOut | null;
};

export type CompleteAnnotationTaskResponse = CompleteAnnotationTaskResponses[keyof CompleteAnnotationTaskResponses];

export type CreateAnnotationData = {
    body: AnnotationCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/create-annotation';
};

export type CreateAnnotationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnnotationError = CreateAnnotationErrors[keyof CreateAnnotationErrors];

export type CreateAnnotationResponses = {
    /**
     * Successful Response
     */
    200: AnnotationOut;
};

export type CreateAnnotationResponse = CreateAnnotationResponses[keyof CreateAnnotationResponses];

export type GetAllAnnotationsForCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations';
};

export type GetAllAnnotationsForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAnnotationsForCampaignError = GetAllAnnotationsForCampaignErrors[keyof GetAllAnnotationsForCampaignErrors];

export type GetAllAnnotationsForCampaignResponses = {
    /**
     * Response Getallannotationsforcampaign
     *
     * Successful Response
     */
    200: Array<AnnotationOut>;
};

export type GetAllAnnotationsForCampaignResponse = GetAllAnnotationsForCampaignResponses[keyof GetAllAnnotationsForCampaignResponses];

export type UpdateAnnotationData = {
    body: AnnotationUpdate;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}/update';
};

export type UpdateAnnotationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnnotationError = UpdateAnnotationErrors[keyof UpdateAnnotationErrors];

export type UpdateAnnotationResponses = {
    /**
     * Successful Response
     */
    200: AnnotationOut;
};

export type UpdateAnnotationResponse = UpdateAnnotationResponses[keyof UpdateAnnotationResponses];

export type DeleteAnnotationData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/annotations/{annotation_id}';
};

export type DeleteAnnotationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnnotationError = DeleteAnnotationErrors[keyof DeleteAnnotationErrors];

export type DeleteAnnotationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAnnotationResponse = DeleteAnnotationResponses[keyof DeleteAnnotationResponses];

export type ExportAnnotationsData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/export-annotations';
};

export type ExportAnnotationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportAnnotationsError = ExportAnnotationsErrors[keyof ExportAnnotationsErrors];

export type ExportAnnotationsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IngestAnnotationTaskFromCsvData = {
    body: BodyIngestAnnotationTaskFromCsv;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/ingest-annotation-task-csv';
};

export type IngestAnnotationTaskFromCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestAnnotationTaskFromCsvError = IngestAnnotationTaskFromCsvErrors[keyof IngestAnnotationTaskFromCsvErrors];

export type IngestAnnotationTaskFromCsvResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTimeseriesForCampaignData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries';
};

export type GetTimeseriesForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeseriesForCampaignError = GetTimeseriesForCampaignErrors[keyof GetTimeseriesForCampaignErrors];

export type GetTimeseriesForCampaignResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesListResponse;
};

export type GetTimeseriesForCampaignResponse = GetTimeseriesForCampaignResponses[keyof GetTimeseriesForCampaignResponses];

export type CreateTimeseriesForCampaignData = {
    body: TimeseriesBulkCreateRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries';
};

export type CreateTimeseriesForCampaignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTimeseriesForCampaignError = CreateTimeseriesForCampaignErrors[keyof CreateTimeseriesForCampaignErrors];

export type CreateTimeseriesForCampaignResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesBulkCreateResponse;
};

export type CreateTimeseriesForCampaignResponse = CreateTimeseriesForCampaignResponses[keyof CreateTimeseriesForCampaignResponses];

export type GetTimeseriesCreationOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/timeseries/create-options';
};

export type GetTimeseriesCreationOptionsResponses = {
    /**
     * Successful Response
     */
    200: TimeSeriesOptionsOut;
};

export type GetTimeseriesCreationOptionsResponse = GetTimeseriesCreationOptionsResponses[keyof GetTimeseriesCreationOptionsResponses];

export type GetTimeseriesDataData = {
    body?: never;
    path: {
        /**
         * Timeseries Id
         */
        timeseries_id: number;
        /**
         * Latitude
         */
        latitude: number;
        /**
         * Longitude
         */
        longitude: number;
    };
    query?: never;
    url: '/api/timeseries/{timeseries_id}/{latitude}/{longitude}/data';
};

export type GetTimeseriesDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeseriesDataError = GetTimeseriesDataErrors[keyof GetTimeseriesDataErrors];

export type GetTimeseriesDataResponses = {
    /**
     * Successful Response
     */
    200: TimeseriesDataResponse;
};

export type GetTimeseriesDataResponse = GetTimeseriesDataResponses[keyof GetTimeseriesDataResponses];

export type DeleteTimeseriesData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Timeseries Id
         */
        timeseries_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/timeseries/{timeseries_id}';
};

export type DeleteTimeseriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTimeseriesError = DeleteTimeseriesErrors[keyof DeleteTimeseriesErrors];

export type DeleteTimeseriesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTimeseriesResponse = DeleteTimeseriesResponses[keyof DeleteTimeseriesResponses];

export type GenerateTasksFromSamplingData = {
    body: BodyGenerateTasksFromSampling;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/campaigns/{campaign_id}/sampling/generate-tasks';
};

export type GenerateTasksFromSamplingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTasksFromSamplingError = GenerateTasksFromSamplingErrors[keyof GenerateTasksFromSamplingErrors];

export type GenerateTasksFromSamplingResponses = {
    /**
     * Successful Response
     */
    200: GenerateTasksResponse;
};

export type GenerateTasksFromSamplingResponse = GenerateTasksFromSamplingResponses[keyof GenerateTasksFromSamplingResponses];

export type CreateImageryData = {
    body: ImageryBulkCreate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery';
};

export type CreateImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateImageryError = CreateImageryErrors[keyof CreateImageryErrors];

export type CreateImageryResponses = {
    /**
     * Successful Response
     */
    200: CreateImageryResponse;
};

export type CreateImageryResponse2 = CreateImageryResponses[keyof CreateImageryResponses];

export type DeleteImageryData = {
    body?: never;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Imagery Id
         */
        imagery_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/{imagery_id}';
};

export type DeleteImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteImageryError = DeleteImageryErrors[keyof DeleteImageryErrors];

export type DeleteImageryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteImageryResponse = DeleteImageryResponses[keyof DeleteImageryResponses];

export type UpdateImageryData = {
    body: ImageryUpdate;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
        /**
         * Imagery Id
         */
        imagery_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/imagery/{imagery_id}';
};

export type UpdateImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateImageryError = UpdateImageryErrors[keyof UpdateImageryErrors];

export type UpdateImageryResponses = {
    /**
     * Successful Response
     */
    200: ImageryOut;
};

export type UpdateImageryResponse = UpdateImageryResponses[keyof UpdateImageryResponses];

export type CreateNewCanvasLayoutForImageryData = {
    body: CanvasLayoutCreateRequest;
    path: {
        /**
         * Campaign Id
         */
        campaign_id: number;
    };
    query?: never;
    url: '/api/{campaign_id}/new-layout';
};

export type CreateNewCanvasLayoutForImageryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewCanvasLayoutForImageryError = CreateNewCanvasLayoutForImageryErrors[keyof CreateNewCanvasLayoutForImageryErrors];

export type CreateNewCanvasLayoutForImageryResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};
